% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\usepackage{float}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Homework 4},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Homework 4}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\subsubsection{Definitions}\label{definitions}

Define the following terms/concepts

\begin{itemize}
\item
  a.) Describe the central limit theorem and its significance to the
  sampling distribution for a sample proportion or mean - {The Central
  Limit Theorem (CLT) is a fundamental concept in statistics that states
  that the sampling distribution of the sample mean or sample proportion
  approaches a normal distribution as the sample size increases,
  regardless of the shape of the population distribution, as long as the
  sample size is sufficiently large.}
\item
  b.) Margin of error - {The margin of error is a measure of the
  uncertainty or precision associated with estimating a population
  parameter (such as a population mean or proportion). It quantifies the
  amount by which a sample estimate might deviate from the true
  population parameter.}
\item
  c.) Describe the ``basic form'' of a confidence interval - {Point
  estimate \(\pm\) Standard score \(\times\) Standard error} which can
  also be written as {Point estimate \(\pm\) Margin of error}
\item
  d.) Confidence level - {the probability that the interval will contain
  the true parameter value before the data are gathered}
\item
  e.) Critical value - {The point on the distribution of the test
  statistic that defines a set of values that call for rejecting the
  null hypothesis - i.e the value which defines the rejection region of
  a test}
\item
  f.) When are \(t\)-distribution and standard normal distribution
  approximately the same shape? - {The \(t\)-distribution and the
  standard normal distribution are approximately the same shape when the
  sample size is large, typically considered to be greater than 30. }
\item
  g.) How are the degrees of freedom of a \(t\)-distribution related to
  its shape? - {As the degrees of freedom increase, the
  \(t\)-distribution becomes more similar to the standard normal
  distribution, with lighter tails.}
\item
  h.) Significance level - {The significance level is a predetermined
  threshold used in statistical hypothesis testing to determine the
  level of evidence required to reject the null hypothesis}
\item
  i.) Rejection region - { The area in the tail (or tails) of the
  distribution of the test statistic for which a result is deemed
  statistically significant}
\end{itemize}

\subsubsection{\texorpdfstring{Finding probabilities from the \(t\) and
\(z\)
distributions}{Finding probabilities from the t and z distributions}}\label{finding-probabilities-from-the-t-and-z-distributions}

\(\bf (1)\) Use the appropriate table to find the probability of each
\(z\) or \(t\) score.

\begin{itemize}
\item
  a.) \(P(Z > 1.3)\) { \(=1-P(Z\leq 1.3) = 0.097\) }
\item
  b.) \(P(Z \leq 0.33)\) { \(=0.629\) }
\item
  c.) \(P(Z \leq -2.1)\) { \(=0.018\) }
\item
  d.) \(P(t > 1.97)\) with 5 degrees of freedom {
  \(= 1 - P(t \leq 1.97) = 0.053\) }
\item
  e.) \(P(t \leq 2.9)\) with 2 degrees of freedom { \(= 0.949\) }
\item
  f.) \(P(t \geq -0.98)\) with 8 degrees of freedom {
  \(= 1 - P(t < -0.98) = 0.822\) }
\end{itemize}

\subsubsection{\texorpdfstring{Finding standard scores and
\(\alpha\)}{Finding standard scores and \textbackslash alpha}}\label{finding-standard-scores-and-alpha}

\(\bf (2)\) Fill in the table below with the corresponding \(\alpha\)
level and critical value for each confidence interval for a population
proportion.

\begin{table}[H]
\centering\centering
\begin{tabular}{ccc}
\toprule
Confidence Level & $\alpha$ & critical value: $z_{1-\alpha/2}$\\
\midrule
\cellcolor{gray!10}{$90\%$} & \cellcolor{gray!10}{$\color{red}{0.1}$} & \cellcolor{gray!10}{$\color{red}{1.645}$}\\
$88\%$ & $\color{red}{0.12}$ & $\color{red}{1.555}$\\
\cellcolor{gray!10}{$97\%$} & \cellcolor{gray!10}{$\color{red}{0.03}$} & \cellcolor{gray!10}{$\color{red}{2.17}$}\\
$96\%$ & $\color{red}{0.04}$ & $\color{red}{2.054}$\\
\cellcolor{gray!10}{$78\%$} & \cellcolor{gray!10}{$\color{red}{0.22}$} & \cellcolor{gray!10}{$\color{red}{1.227}$}\\
\addlinespace
$99\%$ & $\color{red}{0.01}$ & $\color{red}{2.576}$\\
\bottomrule
\end{tabular}
\end{table}

\(\bf (3)\) Fill in the table below with the corresponding \(\alpha\)
level and critical value for each confidence interval for a population
mean.

\begin{table}[H]
\centering\centering
\begin{tabular}{cccc}
\toprule
Confidence Level & Sample size & $\alpha$ & critical value: $t_{n-1, 1-\alpha/2}$\\
\midrule
\cellcolor{gray!10}{$92\%$} & \cellcolor{gray!10}{$n = 5$} & \cellcolor{gray!10}{$\color{red}{0.08}$} & \cellcolor{gray!10}{$\color{red}{2.333}$}\\
$86\%$ & $n = 8$ & $\color{red}{0.14}$ & $\color{red}{1.664}$\\
\cellcolor{gray!10}{$98\%$} & \cellcolor{gray!10}{$n = 11$} & \cellcolor{gray!10}{$\color{red}{0.02}$} & \cellcolor{gray!10}{$\color{red}{2.764}$}\\
$99.9\%$ & $n = 14$ & $\color{red}{0.001}$ & $\color{red}{4.221}$\\
\cellcolor{gray!10}{$82\%$} & \cellcolor{gray!10}{$n = 40$} & \cellcolor{gray!10}{$\color{red}{0.18}$} & \cellcolor{gray!10}{$\color{red}{1.365}$}\\
\addlinespace
$95\%$ & $n = 13$ & $\color{red}{0.05}$ & $\color{red}{2.179}$\\
\bottomrule
\end{tabular}
\end{table}

\section{Confidence intervals}\label{confidence-intervals}

\subsubsection{\texorpdfstring{Confidence intervals for a population
proportion
\(p\)}{Confidence intervals for a population proportion p}}\label{confidence-intervals-for-a-population-proportion-p}

\(\bf (4)\) A survey conducted by the state of Georgia surveyed college
students as part of a larger effort to characterize student behavior
(Agresti and Franklin 2007). One of the questions in the survey asked
students to report their political party affiliation. The table below
summarizes the proportion of students who reported being Republican,
Democrat, or Independent.

\begin{table}[H]
\centering\centering
\begin{tabular}{lrr}
\toprule
Political Party Affiliation & Count & $\hat{p}$\\
\midrule
\cellcolor{gray!10}{Democrat} & \cellcolor{gray!10}{8} & \cellcolor{gray!10}{0.14}\\
Republican & 36 & 0.61\\
\cellcolor{gray!10}{Independent} & \cellcolor{gray!10}{15} & \cellcolor{gray!10}{0.25}\\
\bottomrule
\end{tabular}
\end{table}

Using the table above, construct a \(90\%\) confidence interval for the
proportion of Independent college student voters in the state of
Georgia.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sample.size }\OtherTok{=}\NormalTok{ (}\DecValTok{8}\SpecialCharTok{+}\DecValTok{36}\SpecialCharTok{+}\DecValTok{15}\NormalTok{)}
\NormalTok{estimate }\OtherTok{=} \DecValTok{15}\SpecialCharTok{/}\NormalTok{sample.size}
\NormalTok{confidence.lvl }\OtherTok{=} \FloatTok{0.9}

\NormalTok{CI }\OtherTok{=} \FunctionTok{one.sample.prop.CI}\NormalTok{(}\AttributeTok{phat =}\NormalTok{ estimate, }
                        \AttributeTok{n =}\NormalTok{ sample.size, }
                        \AttributeTok{alpha =} \DecValTok{1}\SpecialCharTok{{-}}\NormalTok{confidence.lvl, }
                        \AttributeTok{verbose =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] --------------------------------------------------
## [1] Estimate = 0.2542
## [1] Critical Value  = 1.6449
## [1] Estimated Standard Error = 0.0567
## [1] Margin of error = 0.0932
## [1] 90 % CI = [0.161,0.3475]
## [1] --------------------------------------------------
\end{verbatim}

\(\bf (5)\) As part of an effort to improve health services, a health
club in the United Kingdom asked club members to complete an online
survey (de Vries 2023). One of the survey questions asked customers to
rate their satisfaction level on a likert scale. The results of this
survey question are summarized below

\begin{table}[H]
\centering\centering
\caption{\label{tab:unnamed-chunk-5}Customer responses for the survey question "How satisfied are you with your membership of the organisation overall?"}
\centering
\begin{tabular}[t]{lrr}
\toprule
Response & Count & $\hat{p}$\\
\midrule
\cellcolor{gray!10}{Completely dissatisfied} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{0.00}\\
Very dissatisfied & 0 & 0.00\\
\cellcolor{gray!10}{Dissatisfied} & \cellcolor{gray!10}{3} & \cellcolor{gray!10}{0.01}\\
Neutral & 20 & 0.09\\
\cellcolor{gray!10}{Satisfied} & \cellcolor{gray!10}{64} & \cellcolor{gray!10}{0.30}\\
\addlinespace
Very satisfied & 109 & 0.51\\
\cellcolor{gray!10}{Completely satisfied} & \cellcolor{gray!10}{19} & \cellcolor{gray!10}{0.09}\\
\bottomrule
\end{tabular}
\end{table}

Using the table above, construct a \(95\%\) confidence interval for the
proportion of customers that are ``very satisfied'' or more.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sample.size }\OtherTok{=}\NormalTok{ (}\DecValTok{3}\SpecialCharTok{+}\DecValTok{20}\SpecialCharTok{+}\DecValTok{64}\SpecialCharTok{+}\DecValTok{109}\SpecialCharTok{+}\DecValTok{19}\NormalTok{)}
\NormalTok{very.satisfied }\OtherTok{=} \DecValTok{109}
\NormalTok{completely.satisfied }\OtherTok{=} \DecValTok{19}
\NormalTok{estimate }\OtherTok{=}\NormalTok{ (very.satisfied}\SpecialCharTok{+}\NormalTok{completely.satisfied)}\SpecialCharTok{/}\NormalTok{sample.size}
\NormalTok{confidence.lvl }\OtherTok{=} \FloatTok{0.95}

\NormalTok{CI }\OtherTok{=} \FunctionTok{one.sample.prop.CI}\NormalTok{(}\AttributeTok{phat =}\NormalTok{ estimate, }
                        \AttributeTok{n =}\NormalTok{ sample.size, }
                        \AttributeTok{alpha =} \DecValTok{1}\SpecialCharTok{{-}}\NormalTok{confidence.lvl, }
                        \AttributeTok{verbose =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] --------------------------------------------------
## [1] Estimate = 0.5953
## [1] Critical Value  = 1.96
## [1] Estimated Standard Error = 0.0335
## [1] Margin of error = 0.0656
## [1] 95 % CI = [0.5297,0.661]
## [1] --------------------------------------------------
\end{verbatim}

\subsubsection{\texorpdfstring{Confidence intervals for a population
mean
\(\mu\)}{Confidence intervals for a population mean \textbackslash mu}}\label{confidence-intervals-for-a-population-mean-mu}

\(\bf (6)\) The following table summarizes variables from a random
sample of \(25\) observations from a dataset concerning housing in
California taken from the 1990 census. The full dataset is featured in
Aurélien Géron's book `Hands-On Machine learning with Scikit-Learn and
TensorFlow' (Géron 2022). Use the table to answer parts (a) and (b)

\begin{table}[H]
\centering\centering
\caption{\label{tab:unnamed-chunk-7}Summary statistics for housing data in California from the 1990 census. Estimates are derived from a random sample of 25 observations from Aurélien Géron's dataset featured in 'Hands-On Machine learning with Scikit-Learn and TensorFlow', originally comprising observations from over 20,000 districts in California}
\centering
\begin{tabular}[t]{lrr}
\toprule
Variable & Sample Mean & Sample Standard Deviation\\
\midrule
\cellcolor{gray!10}{Median Age of Houses (per block)} & \cellcolor{gray!10}{24.28} & \cellcolor{gray!10}{13.56}\\
Total Rooms (per block) & 3263.72 & 2105.99\\
\cellcolor{gray!10}{Total Bedrooms (per block)} & \cellcolor{gray!10}{640.52} & \cellcolor{gray!10}{380.55}\\
Population of District & 1861.68 & 1193.30\\
\cellcolor{gray!10}{Number of Households (per block)} & \cellcolor{gray!10}{584.24} & \cellcolor{gray!10}{330.38}\\
\addlinespace
Median Family Income (in tens of thousands of USD) & 3.74 & 1.54\\
\cellcolor{gray!10}{Median House value (USD)} & \cellcolor{gray!10}{179320.04} & \cellcolor{gray!10}{109450.56}\\
\bottomrule
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  a.) Construct and interpret a \(95\%\) confidence interval for the
  average median family income for households in California in 1990
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sample.size }\OtherTok{=} \DecValTok{25}
\NormalTok{sample.mean }\OtherTok{=} \FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(hss}\SpecialCharTok{$}\NormalTok{median\_income), }\DecValTok{2}\NormalTok{)}\SpecialCharTok{*}\DecValTok{10000} \CommentTok{\#converting estimate to USD}
\NormalTok{sample.sd }\OtherTok{=}  \FunctionTok{round}\NormalTok{(}\FunctionTok{sd}\NormalTok{(hss}\SpecialCharTok{$}\NormalTok{median\_income), }\DecValTok{2}\NormalTok{)}\SpecialCharTok{*}\DecValTok{10000} \CommentTok{\#converting standard deviation to USD}
\NormalTok{confidence.lvl }\OtherTok{=} \FloatTok{0.95}

\NormalTok{CI }\OtherTok{=} \FunctionTok{one.sample.t.CI}\NormalTok{(}\AttributeTok{xbar =}\NormalTok{ sample.mean,}
                     \AttributeTok{s =}\NormalTok{ sample.sd,}
                     \AttributeTok{n =}\NormalTok{ sample.size,}
                     \AttributeTok{alpha =} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ confidence.lvl,}
                     \AttributeTok{verbose =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] --------------------------------------------------
## [1] Estimate = 37400
## [1] Critical Value  = 2.0639
## [1] Estimated Standard Error = 3080
## [1] Margin of error = 6356.8076
## [1] 95 % CI = [31043.1924,43756.8076]
## [1] --------------------------------------------------
\end{verbatim}

{At the \(95\%\) confidence level, we estimate the average median family
income in California in 1990 to be no less than \$31,043 USD and no more
than \$43,757 USD. If we repeated this sampling procedure many times,
\(95\%\) of the intervals constructed this way would contain the true
average.}

\begin{itemize}
\tightlist
\item
  b.) Construct and interpret a \(99\%\) confidence interval for the
  average number of bedrooms per block in California in 1990
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sample.size }\OtherTok{=} \DecValTok{25}
\NormalTok{sample.mean }\OtherTok{=} \FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(hss}\SpecialCharTok{$}\NormalTok{total\_bedrooms), }\DecValTok{2}\NormalTok{)}
\NormalTok{sample.sd }\OtherTok{=}  \FunctionTok{round}\NormalTok{(}\FunctionTok{sd}\NormalTok{(hss}\SpecialCharTok{$}\NormalTok{total\_bedrooms), }\DecValTok{2}\NormalTok{)}
\NormalTok{confidence.lvl }\OtherTok{=} \FloatTok{0.99}

\NormalTok{CI }\OtherTok{=} \FunctionTok{one.sample.t.CI}\NormalTok{(}\AttributeTok{xbar =}\NormalTok{ sample.mean,}
                     \AttributeTok{s =}\NormalTok{ sample.sd,}
                     \AttributeTok{n =}\NormalTok{ sample.size,}
                     \AttributeTok{alpha =} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ confidence.lvl,}
                     \AttributeTok{verbose =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] --------------------------------------------------
## [1] Estimate = 640.52
## [1] Critical Value  = 2.7969
## [1] Estimated Standard Error = 76.11
## [1] Margin of error = 212.8751
## [1] 99 % CI = [427.6449,853.3951]
## [1] --------------------------------------------------
\end{verbatim}

{At the \(99\%\) confidence level, we estimate the average number of
bedrooms per block in California in 1990 to be no less than 427.6 and no
more than 853.4. If we repeated this sampling procedure many times,
\(99\%\) of the intervals constructed this way would contain the true
average.}

\subsubsection{Choosing a minimum sample
size}\label{choosing-a-minimum-sample-size}

\(\bf (7)\) According to a 2023 study published by the Saudi Heart
Association, a survey of college students from Taibah University in
Medina, Saudi Arabia, found that \(24\%\) of students reported using
e-cigarettes (Alzahrani et al. 2023). Assuming a comparable rate of
e-cigarette use in the U.S., what sample size is required to estimate
the proportion of college students who use e-cigarettes at the \(95\%\)
confidence level and within a margin of error of \(1.5\%\)?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{=} \FloatTok{0.015} \CommentTok{\#desired margin of error}
\NormalTok{p }\OtherTok{=} \FloatTok{0.24} \CommentTok{\#expected proportion of e{-}cigarette use based on Saudi Study}
\NormalTok{confidence.lvl }\OtherTok{=} \FloatTok{0.95}
\NormalTok{alpha }\OtherTok{=} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ confidence.lvl}

\NormalTok{z }\OtherTok{=} \FunctionTok{qnorm}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha}\SpecialCharTok{/}\DecValTok{2}\NormalTok{) }\CommentTok{\#standard score for confidence level of 95\%}

\NormalTok{n }\OtherTok{=} \FunctionTok{ceiling}\NormalTok{((z}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{*}\NormalTok{p}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{p))}\SpecialCharTok{/}\NormalTok{m}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\CommentTok{\# compute sample size {-} always round UP}

\CommentTok{\# a sample size of approximately}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{\textquotesingle{}n = \textquotesingle{}}\NormalTok{, n, }\StringTok{\textquotesingle{} observations\textquotesingle{}}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "n = 3115 observations"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#are needed to achieve the desired confidence level and margin of error}
\end{Highlighting}
\end{Shaded}

\(\bf (8)\) Recent concerns over the rise in global infertility have
drawn significant attention to the harmful effects of microplastics,
PFAS, and highly processed foods (Zhang et al. 2022; Agarwal et al.
2015). A study from 2002 published in Fertility and Sterility found that
approximately \(15\%\) of couples worldwide experienced infertility
(Sharlip et al. 2002). Assuming a similar rate of infertility in the
U.S, compute the sample size needed to estimate infertility of U.S
couples at the \(99\%\) confidence level and within a margin of error of
\(4\%\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{=} \FloatTok{0.04} \CommentTok{\#desired margin of error}
\NormalTok{p }\OtherTok{=} \FloatTok{0.15} \CommentTok{\#expected proportion of infertile couples based on previous studies}
\NormalTok{confidence.lvl }\OtherTok{=} \FloatTok{0.99}
\NormalTok{alpha }\OtherTok{=} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ confidence.lvl}

\NormalTok{z }\OtherTok{=} \FunctionTok{qnorm}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha}\SpecialCharTok{/}\DecValTok{2}\NormalTok{) }\CommentTok{\#standard score for confidence level of 99\%}

\NormalTok{n }\OtherTok{=} \FunctionTok{ceiling}\NormalTok{((z}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{*}\NormalTok{p}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{p))}\SpecialCharTok{/}\NormalTok{m}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\CommentTok{\# compute sample size {-} always round UP}

\CommentTok{\# a sample size of approximately}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{\textquotesingle{}n = \textquotesingle{}}\NormalTok{, n, }\StringTok{\textquotesingle{} observations\textquotesingle{}}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "n = 529 observations"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#are needed to achieve the desired confidence level and margin of error}
\end{Highlighting}
\end{Shaded}

\subsubsection{Assumptions of
estimators}\label{assumptions-of-estimators}

\(\bf (9)\) Describe the assumptions associated with estimating \(p\)
with \(\hat{p}\)

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  { \textbf{Random Sampling:} The sample must be selected randomly from
  the population of interest. Random sampling ensures that each member
  of the population has an equal chance of being included in the sample,
  allowing for unbiased estimation of the population proportion.}
\item
  { \textbf{Independence:} The observations in the sample must be
  independent of each other. Independence means that the occurrence or
  value of one observation does not influence the occurrence or value of
  another observation in the sample.}
\item
  { \textbf{Large Sample Size (for Asymptotic Normality):} For certain
  statistical methods, such as constructing confidence intervals or
  conducting hypothesis tests, the sample size should be sufficiently
  large. While there is no fixed threshold for what constitutes ``large
  enough,'' a common rule of thumb is that \(np\geq 15\) and
  \(n(1-p)\geq 15\) to ensure the validity of results. }
\end{enumerate}

\(\bf (10)\) Describe the assumptions associated with estimating \(\mu\)
with \(\bar{x}\)

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  { \textbf{Random Sampling:} The sample must be selected randomly from
  the population of interest. Random sampling ensures that each member
  of the population has an equal chance of being included in the sample,
  allowing for unbiased estimation of the population proportion. }
\item
  { \textbf{Independence:} The observations in the sample must be
  independent of each other. Independence means that the occurrence or
  value of one observation does not influence the occurrence or value of
  another observation in the sample. }
\item
  { \textbf{Normality of Population Distribution (for Small Sample
  Sizes):} For small sample sizes (typically less than 30), it is
  assumed that the population from which the sample is drawn follows a
  normal distribution. This assumption is necessary for the validity of
  certain statistical inference methods, such as constructing confidence
  intervals or conducting hypothesis tests. However, the Central Limit
  Theorem suggests that for larger sample sizes, the distribution of the
  sample mean approaches normality regardless of the shape of the
  population distribution. }
\end{enumerate}

\section{Significance testing}\label{significance-testing}

\subsubsection{Stating hypotheses}\label{stating-hypotheses}

\(\bf (11)\) A pharmaceutical company produces a generic version of the
pain reliever ibuprofen, marketing a tablet with a 200 milligram dose.
Concerned about the accuracy of the dosing process, the manufacturer
suspects that the machine filling the tablets may be malfunctioning
leading to a smaller dose in each tablet. The manufacturer wishes to
conduct a significance test to determine if the dose is significantly
lower than 200 milligrams. State the null and alternative hypotheses for
this test

{ The null hypothesis is that the mean dose of a tablet is 200 mg
\[ H_0: \mu_0 = 200\] The alternative hypothesis is that the mean dose
of a tablet is less than 200 mg \[ H_A: \mu < \mu_0 \] }

\(\bf (12)\) A financial institution invests in a pharmaceutical
company, which produces a widely prescribed antidepressant medication
with a market value of \$100 per share. Worried about potential
discrepancies in the market valuation, the institution suspects that
recent market trends may have led to an underestimation of the stock's
value. The institution plans to conduct a significance test to determine
if the stock's value has significantly increased. State the null and
alternative hypotheses for this test.

{ The null hypothesis is that the mean share value is \(\$100\)
\[ H_0: \mu_0 = 100\] The alternative hypothesis is that the mean share
value is greater than \(\$100\) \[ H_A: \mu > \mu_0 \] }

\(\bf (13)\) A semiconductor manufacturing company produces microchips
with a target defect rate of 0.1\% per batch. Concerned about the
quality control process, the company suspects that recent changes in
manufacturing procedures may have resulted in a change in the defect
rate. The company intends to conduct a significance test to determine if
the defect rate is significantly different than the target rate of
0.1\%. State the null and alternative hypotheses for this test.

{ The null hypothesis is that the proportion of defective
semi-conductors is \(0.001\) \[ H_0: p_0 = 0.001\] The alternative
hypothesis is that that the proportion of defective semi-conductors is
not equal to \(0.001\) \[ H_A: p \neq p_0 \] }

\subsubsection{The Decision Rule}\label{the-decision-rule}

\(\bf (14)\) For each set of hypotheses, significance level, and
\(p\)-value. State whether the test rejects or fails to reject the null
hypothesis.

\begin{itemize}
\item
  a.) \(H_0: \mu = 0\); \(H_A: \mu \neq 0\); \(\alpha = 0.01\);
  \(p\)-value \(= 0.0098\) {Decision: reject \(H_0\) because \(p\)-value
  \(<\alpha\) }
\item
  b.) \(H_0: p = 0.5\); \(H_A: p > 0.5\); \(\alpha = 0.05\); \(p\)-value
  \(= 0.086\) {Decision: fail to reject \(H_0\) because \(p\)-value
  \(>\alpha\) }
\item
  c.) \(H_0: \mu = 100\); \(H_A: \mu < 100\); \(\alpha = 0.001\);
  \(p\)-value \(= 0.0015\) {Decision: fail to reject \(H_0\) because
  \(p\)-value \(>\alpha\) }
\item
  d.) \(H_0: p = 0.9\); \(H_A: p \neq 0.9\); \(\alpha = 0.1\);
  \(p\)-value \(= 0.053\) {Decision: reject \(H_0\) because \(p\)-value
  \(<\alpha\) }
\end{itemize}

\(\bf (15)\) For each set of hypotheses, significance level, sample
size, and test statistic. Give the critical value and state whether the
test rejects or fails to reject the null hypothesis.

\begin{itemize}
\item
  a.) \(H_0: \mu = 15\); \(H_A: \mu > 15\); \(n = 33\);
  \(\alpha = 0.05\); \(t_{obs} = 2.13\) { \textbf{critical value:}
  \(t_{32, 0.95 } = 1.69\); \textbf{Decision:} reject \(H_0\) because
  \(t_{obs}>1.69\) }
\item
  b.) \(H_0: \mu = 0\); \(H_A: \mu \neq 0\); \(n = 14\);
  \(\alpha = 0.01\) ; \(t_{obs} = -4.1\) { \textbf{critical value:}
  \(t_{13, 0.995} = 3.01\); \textbf{Decision:} reject \(H_0\) because
  \(| t_{obs}| > 3.01\)}
\item
  c.) \(H_0: p = 0.5\); \(H_A: p < 0.5\); \(n = 120\); \(\alpha = 0.1\);
  \(Z_{obs} = -1.5\) { \textbf{critical value:} \(Z_{0.1} = -1.28\);
  \textbf{Decision:} reject \(H_0\) because \(Z_{obs} < -1.28\)}
\item
  d.) \(H_0: p = 0.05\); \(H_A: p \neq 0.05\); \(n = 60\);
  \(\alpha = 0.03\); \(Z_{obs} = 1.95\) { \textbf{critical value:}
  \(Z_{0.985}= 2.17\); \textbf{Decision:} fail to reject \(H_0\) because
  \(|Z_{obs}|\) is not greater than \(2.17\)}
\end{itemize}

\subsubsection{\texorpdfstring{Hypothesis tests for a population
proportion
\(p\)}{Hypothesis tests for a population proportion p}}\label{hypothesis-tests-for-a-population-proportion-p}

\(\bf (16)\) A toy manufacturer claims that \(50\%\) of their toy robots
are defect-free. However, a quality control inspector suspects that the
actual proportion of defect-free robots is different from what the
manufacturer claims. To investigate, the inspector randomly selects
\(100\) toy robots from a production batch and examines them for
defects. After the inspection, the inspector finds that \(40\) out of
the \(100\) toy robots are defect-free. To test their suspicion, they
set up a two-tailed hypothesis test with a significance level
\(\alpha = 0.1\) and hypotheses \(H_0: p_0 = 0.5\) (manufacturer's
claim) \(H_A: p \neq p_0\).

\begin{itemize}
\tightlist
\item
  a.) Using the significance level above, is there enough evidence to
  conclude that the proportion of defect-free toy robots is different
  from the manufacturer's claim?
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test.type }\OtherTok{=} \StringTok{\textquotesingle{}two.tail\textquotesingle{}}
\NormalTok{null.value }\OtherTok{=} \FloatTok{0.5}
\NormalTok{sample.size }\OtherTok{=} \DecValTok{100}
\NormalTok{estimated.proportion }\OtherTok{=} \DecValTok{40}\SpecialCharTok{/}\DecValTok{100}
\NormalTok{significance.lvl }\OtherTok{=} \FloatTok{0.1}

\FunctionTok{one.sample.prop.test}\NormalTok{(}\AttributeTok{p0 =}\NormalTok{ null.value,}
                     \AttributeTok{phat =}\NormalTok{ estimated.proportion,}
                     \AttributeTok{n =}\NormalTok{ sample.size,}
                     \AttributeTok{alpha =}\NormalTok{ significance.lvl,}
                     \AttributeTok{test =}\NormalTok{ test.type,}
                     \AttributeTok{verbose =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] ==================== test results ====================
## [1] test type = two.tail
## [1] H0: p0 = 0.5
## [1] HA: p != 0.5
## [1] estimate = 0.4
## [1] Estimated Standard Error = 0.05
## [1] Critical Value = 1.6449
## [1] 90% CI = [0.3194,0.4806]
## [1] Test statistic = -2
## [1] Pvalue = 0.0455
## [1] Decision: reject H0
## [1] ======================================================
\end{verbatim}

{The test statistic is
\(Z_{obs} = \frac{0.40 - 0.50}{\sqrt{0.5(1-0.5)/100}} = -2.00\) with a
two-tailed \(p\)-value of \(0.0455\). Since \(0.0455 < \alpha = 0.1\)
(equivalently, \(|Z_{obs}| = 2.00 > 1.645\)), at the \(10\%\)
significance level we reject the null hypothesis and conclude that the
proportion of defect-free toy robots is significantly different from the
manufacturer's claim of \(0.5\) }

\(\bf (17)\) A pharmaceutical company has developed a new drug designed
to cure a specific bacterial infection. They claim that their drug is
effective, with a cure rate of \(20\%\). However, a group of independent
researchers believes that the cure rate is less than what the
pharmaceutical company claims. To investigate, the researchers conduct a
clinical trial on \(300\) patients suffering from the bacterial
infection. After the trial, they find that \(70\) out of the \(300\)
patients were cured using the new drug. To test their suspicion, they
set up a hypothesis test with a significance level of \(\alpha = 0.05\)
with \(H_0: p_0 = 0.2\), \(H_A: p < p_0\)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test.type }\OtherTok{=} \StringTok{\textquotesingle{}lower.tail\textquotesingle{}}
\NormalTok{null.value }\OtherTok{=} \FloatTok{0.2}
\NormalTok{sample.size }\OtherTok{=} \DecValTok{300}
\NormalTok{estimated.proportion }\OtherTok{=} \DecValTok{70}\SpecialCharTok{/}\DecValTok{300}
\NormalTok{significance.lvl }\OtherTok{=} \FloatTok{0.05}

\FunctionTok{one.sample.prop.test}\NormalTok{(}\AttributeTok{p0 =}\NormalTok{ null.value,}
                     \AttributeTok{phat =}\NormalTok{ estimated.proportion,}
                     \AttributeTok{n =}\NormalTok{ sample.size,}
                     \AttributeTok{alpha =}\NormalTok{ significance.lvl,}
                     \AttributeTok{test =}\NormalTok{ test.type,}
                     \AttributeTok{verbose =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] ==================== test results ====================
## [1] test type = lower.tail
## [1] H0: p0 = 0.2
## [1] HA: p < 0.2
## [1] estimate = 0.2333
## [1] Estimated Standard Error = 0.0231
## [1] Critical Value = -1.6449
## [1] 95% CI = [0.1855,0.2812]
## [1] Test statistic = 1.4434
## [1] Pvalue = 0.9255
## [1] Decision: fail to reject H0
## [1] ======================================================
\end{verbatim}

\begin{itemize}
\item
  a.) Compute the critical value for this test

  {the critical value is \(Z_{\alpha} = -1.64\)}
\item
  b.) Compute the test statistic \(Z_{obs}\)

  {the test statistic is
  \[Z_{obs} = \frac{0.233 - 0.2}{\sqrt{\frac{0.2(1-0.2)}{300}}} = 1.44 \]
  }
\item
  c.) Compute the \(p\)-value
\end{itemize}

{the \(p\)-value is \[P(Z < Z_{obs} | H_0 \ \text{True}) = 0.9255 \] }

\begin{itemize}
\tightlist
\item
  d.) Is there enough evidence to conclude that the cure rate of the new
  drug is less than the rate claimed by the pharmaceutical company?
\end{itemize}

{At the \(5\%\) significance level, we fail to reject the null
hypothesis and conclude that the proportion of patients cured by the
drug is not significantly less than \(0.2\) }

\subsubsection{\texorpdfstring{Hypothesis tests for a population mean
\(\mu\)}{Hypothesis tests for a population mean \textbackslash mu}}\label{hypothesis-tests-for-a-population-mean-mu}

\(\bf (18)\) A soft drink company claims that their new ``Zero Sugar''
soda contains zero grams of added sugar per 12-ounce can. To test this
claim, a random sample of \(25\) cans of this soda is selected. The
sample mean is found to be \(1.3\) grams of added sugar per can, with a
standard deviation of \(0.5\) grams. To determine if there is enough
evidence to reject the company's claim and conclude that the soda does
not contain zero grams of added sugar per can, a group of researchers is
interested in testing the following hypotheses: \(H_0: \mu_0 = 0\),
\(H_A: \mu \neq \mu_0\) at the \(\alpha = 0.01\) significance level.

\begin{itemize}
\tightlist
\item
  a.) Using the significance level above, is there evidence that the
  soda produced by the soft drink company contains added sugars?
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#The null hypothesis is H\_0: m0 = 0 (no added sugar)}

\CommentTok{\#The alternative hypothesis is H\_A: m \textgreater{} m0 {-} this is the best option since it does not }
\CommentTok{\#make since check for less than 0 added sugar. }

\NormalTok{test.type }\OtherTok{=} \StringTok{\textquotesingle{}upper.tail\textquotesingle{}}
\NormalTok{null.value }\OtherTok{=} \DecValTok{0}
\NormalTok{sample.mean }\OtherTok{=} \FloatTok{1.3}
\NormalTok{sample.sd }\OtherTok{=} \FloatTok{0.5}
\NormalTok{sample.size }\OtherTok{=} \DecValTok{25}
\NormalTok{significance.lvl }\OtherTok{=} \FloatTok{0.01}

\FunctionTok{one.sample.t.test}\NormalTok{(}\AttributeTok{m0 =}\NormalTok{ null.value,}
                  \AttributeTok{xbar =}\NormalTok{ sample.mean,}
                  \AttributeTok{s =}\NormalTok{ sample.sd,}
                  \AttributeTok{n =}\NormalTok{ sample.size, }
                  \AttributeTok{alpha =}\NormalTok{ significance.lvl,}
                  \AttributeTok{test =}\NormalTok{ test.type,}
                  \AttributeTok{verbose =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] ==================== test results ====================
## [1] test type = upper.tail
## [1] H0: m0 = 0
## [1] HA: m > 0
## [1] Estimate = 1.3
## [1] Estimated Standard Error = 0.1
## [1] Critical Value = 2.4922
## [1] 99% CI = [1.0203,1.5797]
## [1] Test statistic = 13
## [1] Degrees of Freedom = 24
## [1] Pvalue = 0
## [1] Decision: reject H0
## [1] ======================================================
\end{verbatim}

{At the \(1\%\) significance level, we reject the null hypothesis and
conclude that the soda produced by the company contains significant
amounts of added sugars }

\(\bf (19)\) A group of botanists is studying the growth rate of Venus
fly traps in a controlled greenhouse environment. Based on historical
data, the typical growth rate of Venus fly traps is believed to be
\(100\) millimeters per year. The botanists suspect that the current
growth rate in their greenhouse is higher than this historical value. To
investigate, they take a random sample of \(40\) Venus fly traps and
measure their growth rates over a year. After the study, they find that
the sample mean growth rate for the \(40\) Venus fly traps is \(105\)
millimeters per year with a standard deviation of \(12\)mm. To test
their suspicion, they set up a hypothesis test with a significance level
of \(\alpha = 0.05\)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test.type }\OtherTok{=} \StringTok{\textquotesingle{}upper.tail\textquotesingle{}}
\NormalTok{null.value }\OtherTok{=} \DecValTok{100}
\NormalTok{sample.mean }\OtherTok{=} \DecValTok{105}
\NormalTok{sample.sd }\OtherTok{=} \DecValTok{12}
\NormalTok{sample.size }\OtherTok{=} \DecValTok{40}
\NormalTok{significance.lvl }\OtherTok{=} \FloatTok{0.05}

\FunctionTok{one.sample.t.test}\NormalTok{(}\AttributeTok{m0 =}\NormalTok{ null.value,}
                  \AttributeTok{xbar =}\NormalTok{ sample.mean,}
                  \AttributeTok{s =}\NormalTok{ sample.sd,}
                  \AttributeTok{n =}\NormalTok{ sample.size, }
                  \AttributeTok{alpha =}\NormalTok{ significance.lvl,}
                  \AttributeTok{test =}\NormalTok{ test.type,}
                  \AttributeTok{verbose =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] ==================== test results ====================
## [1] test type = upper.tail
## [1] H0: m0 = 100
## [1] HA: m > 100
## [1] Estimate = 105
## [1] Estimated Standard Error = 1.8974
## [1] Critical Value = 1.6849
## [1] 95% CI = [101.1622,108.8378]
## [1] Test statistic = 2.6352
## [1] Degrees of Freedom = 39
## [1] Pvalue = 0.006
## [1] Decision: reject H0
## [1] ======================================================
\end{verbatim}

\begin{itemize}
\tightlist
\item
  a.) State the null and alternative hypotheses
\end{itemize}

{The null hypothesis is that the mean growth rate of venus fly traps is
\(100\)mm per year. \[H_0: \mu_0 = 100 \] The alternative hypothesis is
that the growth rate is higher than \(100\)mm per year
\[H_A: \mu > 100\] }

\begin{itemize}
\tightlist
\item
  b.) Compute the critical value for this test
\end{itemize}

{The critical value is \(t_{39, 0.95} = 1.68\)}

\begin{itemize}
\tightlist
\item
  c.) Compute the test statistic \(t_{obs}\)
\end{itemize}

{ \[t_{obs} = \frac{105 - 100}{12/\sqrt{40}} \approx 2.64 \] }

\begin{itemize}
\tightlist
\item
  d.) Compute the \(p\)-value
\end{itemize}

{The \(p\)-value is given by
\[P(t > t_{obs}| H_0 \ \text{true}) = 1 - P(t \leq t_{obs}| H_0 \ \text{true}) = 1 - 0.994 = 0.006\]
}

\begin{itemize}
\tightlist
\item
  e.) Is there enough evidence to conclude that the current growth rate
  of Venus fly traps in the greenhouse is higher than the historical
  value of \(100\) millimeters per year?
\end{itemize}

{At the \(5\%\) significance level, we reject the null hypothesis and
conclude that the current growth rate is significantly higher than 100
mm per year.}

\newpage

\section*{References}\label{references}
\addcontentsline{toc}{section}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-agarwal2015unique}
Agarwal, Ashok, Aditi Mulgund, Alaa Hamada, and Michelle Renee Chyatte.
2015. {``A Unique View on Male Infertility Around the Globe.''}
\emph{Reproductive Biology and Endocrinology} 13: 1--9.

\bibitem[\citeproctext]{ref-agresti2007art}
Agresti, Alan, and Christine Franklin. 2007. {``The Art and Science of
Learning from Data.''} \emph{Upper Saddle River, New Jersey} 88.

\bibitem[\citeproctext]{ref-alzahrani2023prevalence}
Alzahrani, Talal, Marwan F Alhazmi, Ahmed N Alharbi, Feras T AlAhmadi,
Amer N Alhubayshi, and Bader A Alzahrani. 2023. {``The Prevalence of
Electronic Cigarette Use Among College Students of Taibah University and
Symptoms of Cardiovascular Disease.''} \emph{Journal of the Saudi Heart
Association} 35 (2): 163.

\bibitem[\citeproctext]{ref-andriesurvey}
de Vries, Andrie. 2023. \emph{Surveydata: Tools to Work with Survey
Data}. \url{https://CRAN.R-project.org/package=surveydata}.

\bibitem[\citeproctext]{ref-geron2022hands}
Géron, Aurélien. 2022. \emph{Hands-on Machine Learning with
Scikit-Learn, Keras, and TensorFlow}. " O'Reilly Media, Inc.".

\bibitem[\citeproctext]{ref-sharlip2002best}
Sharlip, Ira D, Jonathan P Jarow, Arnold M Belker, Larry I Lipshultz,
Mark Sigman, Anthony J Thomas, Peter N Schlegel, et al. 2002. {``Best
Practice Policies for Male Infertility.''} \emph{Fertility and
Sterility} 77 (5): 873--82.

\bibitem[\citeproctext]{ref-zhang2022microplastics}
Zhang, Chenming, Jianshe Chen, Sicheng Ma, Zixue Sun, and Zulong Wang.
2022. {``Microplastics May Be a Significant Cause of Male
Infertility.''} \emph{American Journal of Men's Health} 16 (3):
15579883221096549.

\end{CSLReferences}

\end{document}
