% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{float}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Homework 3 Solutions},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Homework 3 Solutions}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\subsubsection{Definitions}\label{definitions}

Define the following terms/concepts

\begin{itemize}
\item
  a.) Sampling Error - {the difference between a sample estimate and the
  true population parameter it is estimating, which arises because we
  observe only a subset of the population}
\item
  b.) Law of Large Numbers - {A theorem in probability and statistics
  which states that the relative frequency of an event will tend to
  ``approach'' (in some sense) the probability of an event as the number
  of observations increases}
\item
  c.) Sample Space - {the collection of all possible outcomes of a
  random phenomenon or experiment}
\item
  d.) Event - {A set of outcomes of a random phenomenon or experiment -
  that is, any subset of the sample space}
\item
  e.) Union - {the combined outcomes of two events}
\item
  f.) Intersection - {the overlapping outcomes of two events}
\item
  g.) Random Trial - {a process or experiment that can be repeated with
  a well-defined set of possible outcomes.}
\item
  h.) Random Variable - {a function that assigns a numerical value to
  each outcome in the sample space}
\item
  i.) Probability distribution - {a function that gives the
  probabilities of different possible outcomes of a random variable}
\item
  j.) Population distribution - {is the probability distribution for a
  single observation of a random variable}
\item
  k.) Continuous random variable - {A random variable with an
  uncountable number of outcomes}
\item
  l.) Discrete random variable - {A random variable with a countable
  number of outcomes}
\item
  m.) Probability Mass Function - {A function which assigns a
  probability to each outcome of a discrete random variable}
\item
  n.) Probability Density Function - {A function which assigns
  probability density to different outcomes of a continuous random
  variable}
\end{itemize}

\subsection{Simple probability}\label{simple-probability}

\(\bf (1)\) A fair coin is thrown 3 times. What is the probability that
at least one heads is observed?

{ \[P(\text{At least one heads}) = 1-P(\text{No Heads})\] The sample
space of this event is
\[\mathbb{S} = \begin{bmatrix} \text{No heads} = (T,T,T) \\
\text{1 Heads} = (H,T,T),(T,H,T),(T,T,H)  \\
\text{2 Heads} = (H,H,T),(H,T,H),(T,H,H) \\
\text{All Heads} = (H,H,H) \end{bmatrix} \] The sample space consists of
8 possible outcomes and there is only one outcome with ``No Heads''.
\[ P(\text{At least one heads}) = 1-P(\text{No Heads}) = 1-\frac{1}{8} = \frac{7}{8} \]
}

\(\bf (2)\) Suppose that in a class of 30 students, 8 students are in
band, 15 students play a sport, and 5 students are both in band and play
a sport. Let \(A\) be the event that a student is in band and let \(B\)
be the event that a student plays a sport. Create a Venn diagram that
models this situation. What is the probability that a student is in the
band or plays a sport?

\includegraphics{week7homework_solns_files/figure-latex/unnamed-chunk-1-1.pdf}

{Since these events are non-disjoint, we must use the formula for a
union of two non-disjoint events:
\[P(A\cup B) = P(A) + P(B) - P(A\cap B)\]
\[= \frac{8}{30}+\frac{15}{30} - \frac{5}{30} =\frac{18}{30}\]}

\(\bf (3)\) A standard deck of 52 cards contains four suits (Hearts,
Diamonds, Clubs, and Spades). Each suit contains 13 cards (9 numbered
cards and 3 face cards, and an Ace).

\begin{itemize}
\tightlist
\item
  Suppose a single card is drawn at random, what is the probability that
  it is a numbered card?
\end{itemize}

{\[P(\text{Card is numbered}) = \frac{\text{Number of ways to get numbered card}}{\text{Total number of cards}} = \frac{9 \cdot 4}{52} \]}

\begin{itemize}
\tightlist
\item
  What is the probability that the selected card is the Ace of Spades
  (assume independence where necessary)?
\end{itemize}

{Let \(A\) be the event that a card drawn at random is an Ace and \(B\)
be the event that a card drawn at random is a Spades. We are interested
in the \(P(A\cap B)\) and we are told to assume independence. Therefore
\[P(A\cap B) = P(A)\cdot P(B) = \frac{4}{52} \cdot \frac{13}{52} = \frac{1}{52}\]}

\(\bf (4)\) An urn contains 5 green balls, 7 red balls, and 4 yellow
balls. Two balls are selected at random with replacement. What is the
probability that first ball is yellow and the second ball is red?

{Since the balls are selected with replacement the two events are
independent. Therefore, the intersection of the two events: \(A\) first
ball yellow and \(B\) second ball is red is given by
\[P(A\cap B) = \frac{4}{16} \cdot \frac{7}{16}  = \frac{7}{64}\]}

\(\bf (5)\) The probability that it rains \(R\) on a given day in
Moscow, Idaho is \(P(R) = 0.1\). The probability that it is Windy \(W\)
is \(P(W) = 0.2\), and the probability that it is cloudy \(C\) is
\(P(C) = 0.7\). Assume that these three types of weather events are
independent. What is the probability that a given day is Rainy, Cloudy,
and Windy?

{We are told the events are independent and we wish to find the
intersection of \(R\), \(W\) and \(C\):
\[P(R\cap W\cap C) = (0.1)(0.2)(0.7) = 0.014 \]}

\subsection{Sampling Distributions, Means, and
Variances}\label{sampling-distributions-means-and-variances}

\(\bf (6)\) A random variable \(X\) has the following probability
distribution

\begin{table}[H]
\centering\centering
\begin{tabular}{rr}
\toprule
X & P(X)\\
\midrule
\cellcolor{gray!10}{1} & \cellcolor{gray!10}{0.25}\\
2 & 0.25\\
\cellcolor{gray!10}{3} & \cellcolor{gray!10}{0.25}\\
4 & 0.25\\
\bottomrule
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  Derive the sampling distribution for the mean of \(n=2\) observations
  of \(X\)
\end{itemize}

{The sample space for a mean of two observations of \(X\) is given
below.}

\begin{table}[H]
\centering\centering
\begin{tabular}{rrr}
\toprule
Observation 1 & Observation 2 & $\bar{X}$\\
\midrule
\cellcolor{gray!10}{1} & \cellcolor{gray!10}{1} & \cellcolor{gray!10}{1.0}\\
2 & 1 & 1.5\\
\cellcolor{gray!10}{3} & \cellcolor{gray!10}{1} & \cellcolor{gray!10}{2.0}\\
4 & 1 & 2.5\\
\cellcolor{gray!10}{1} & \cellcolor{gray!10}{2} & \cellcolor{gray!10}{1.5}\\
\addlinespace
2 & 2 & 2.0\\
\cellcolor{gray!10}{3} & \cellcolor{gray!10}{2} & \cellcolor{gray!10}{2.5}\\
4 & 2 & 3.0\\
\cellcolor{gray!10}{1} & \cellcolor{gray!10}{3} & \cellcolor{gray!10}{2.0}\\
2 & 3 & 2.5\\
\addlinespace
\cellcolor{gray!10}{3} & \cellcolor{gray!10}{3} & \cellcolor{gray!10}{3.0}\\
4 & 3 & 3.5\\
\cellcolor{gray!10}{1} & \cellcolor{gray!10}{4} & \cellcolor{gray!10}{2.5}\\
2 & 4 & 3.0\\
\cellcolor{gray!10}{3} & \cellcolor{gray!10}{4} & \cellcolor{gray!10}{3.5}\\
\addlinespace
4 & 4 & 4.0\\
\bottomrule
\end{tabular}
\end{table}

{The sampling distribution of \(\bar{X}\) is given by:}

\begin{table}[H]
\centering\centering
\begin{tabular}{rl}
\toprule
$\bar{X}$ & $P(\bar{X})$\\
\midrule
\cellcolor{gray!10}{1.0} & \cellcolor{gray!10}{$\color{red}{1(0.25^2)=0.0625}$}\\
1.5 & $\color{red}{2(0.25^2)=0.125}$\\
\cellcolor{gray!10}{2.0} & \cellcolor{gray!10}{$\color{red}{3(0.25^2)=0.1875}$}\\
2.5 & $\color{red}{4(0.25^2)=0.25}$\\
\cellcolor{gray!10}{3.0} & \cellcolor{gray!10}{$\color{red}{3(0.25^2)=0.1875}$}\\
\addlinespace
3.5 & $\color{red}{2(0.25^2)=0.125}$\\
\cellcolor{gray!10}{4.0} & \cellcolor{gray!10}{$\color{red}{1(0.25^2)=0.0625}$}\\
\bottomrule
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  Compute the mean \(\mu_{\bar{X}}\) and standard deviation
  \(\sigma_{\bar{X}}\) of the sampling distribution of \(\bar{X}\)
\end{itemize}

{Using the sampling distribution of \(\bar{X}\) derived above:
\[\mu_{\bar{X}} =\sum_{\bar{x}} \bar{x}P(\bar{x}) \]
\[= 1(0.0625)+1.5(0.125)+\cdots +3.5(0.125)+4(0.0625)\] \[= 2.5 \]}

{\[\sigma_{\bar{X}} =\sqrt{\sum_{\bar{x}} (\bar{x}-\mu_{\bar{X}})^2P(\bar{x})} \]
\[= \sqrt{(1-2.5)^2(0.0625)+(1.5-2.5)^2(0.125)+\cdots +(3.5-2.5)^2(0.125)+(4-2.5)^2(0.0625)} \]
\[= \sqrt{0.625} \] \[= 0.791\]}

{Note that this agrees with the population values for \(X\) itself:
\(\mu = 2.5\) and \(\sigma = \sqrt{1.25} = 1.118\), and the standard
deviation of the sampling distribution is
\(\sigma/\sqrt{n} = 1.118/\sqrt{2} = 0.791\).}

\(\bf (7)\) A random variable \(Y\) has two possible outcomes. The
outcome \(Y = 1\) occurs with probability \(p = 0.23\). Derive the
sampling distribution for the proportion of outcomes with \(Y = 1\) in a
sample of \(n = 3\) observations of \(Y\).

{The population distribution of \(Y\) is given by:}

\begin{table}[H]
\centering\centering
\begin{tabular}{rr}
\toprule
$Y$ & $P(Y)$\\
\midrule
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{0.77}\\
1 & 0.23\\
\bottomrule
\end{tabular}
\end{table}

{The sample space for the sample proportion of 3 observations of \(Y\)
is given below.}

\begin{table}[H]
\centering\centering
\begin{tabular}{rrrr}
\toprule
Observation 1 & Observation 2 & Observation 3 & $\hat{p}$\\
\midrule
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{0.00}\\
1 & 0 & 0 & 0.33\\
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{1} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{0.33}\\
1 & 1 & 0 & 0.67\\
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{1} & \cellcolor{gray!10}{0.33}\\
\addlinespace
1 & 0 & 1 & 0.67\\
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{1} & \cellcolor{gray!10}{1} & \cellcolor{gray!10}{0.67}\\
1 & 1 & 1 & 1.00\\
\bottomrule
\end{tabular}
\end{table}

{The sampling distribution of \(\hat{p}\) is given by:}

\begin{table}[H]
\centering\centering
\begin{tabular}{rl}
\toprule
$\hat{p}$ & $P(\hat{p})$\\
\midrule
\cellcolor{gray!10}{0.00} & \cellcolor{gray!10}{$\color{red}{1(0.77^3)=0.457}$}\\
0.33 & $\color{red}{3(0.23 \times 0.77^2)=0.409}$\\
\cellcolor{gray!10}{0.67} & \cellcolor{gray!10}{$\color{red}{3(0.23^2\times 0.77)=0.122}$}\\
1.00 & $\color{red}{1(0.23^3)=0.012}$\\
\bottomrule
\end{tabular}
\end{table}

\(\bf (8)\) Consider a survey of tree volume. Suppose that in the
population of trees \(10\%\) have a volume of 10 cubic feet, \(20\%\)
have a volume of 20 cubic feet, \(30\%\) have a volume of 30 cubic feet,
and \(40\%\) have a volume of 40 cubic feet. Let \(X\) denote the volume
of a randomly selected tree, assuming that every tree has an equal
chance of being selected. The probability distribution of \(X\) is given
in the table below.

\begin{table}[H]
\centering\centering
\begin{tabular}{rr}
\toprule
X & P(X)\\
\midrule
\cellcolor{gray!10}{10} & \cellcolor{gray!10}{0.1}\\
20 & 0.2\\
\cellcolor{gray!10}{30} & \cellcolor{gray!10}{0.3}\\
40 & 0.4\\
\bottomrule
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  Confirm that \(X\) has a mean of \(\mu = 30\) cubic feet and a
  standard deviation of \(\sigma = 10\) cubic feet by computing them
  yourself.
\end{itemize}

{\[\mu = \sum_x xP(x)\] \[ = 10(0.1)+20(0.2)+30(0.3)+40(0.4)\]
\[ = 30\]}

{\[\sigma = \sqrt{\sum_x (x-\mu)^2P(x)}\]
\[ = \sqrt{(10-30)^2(0.1)+(20-30)^2(0.2)+(30-30)^2(0.3)+(40-30)^2(0.4)}\]
\[ = \sqrt{100}\] \[ = 10\]}

\begin{itemize}
\tightlist
\item
  Derive the sampling distribution for the mean tree volume in a sample
  of \(n = 2\) trees.
\end{itemize}

{The sample space for the sample mean of 2 observations of tree volume
is given below.}

\begin{table}[H]
\centering\centering
\begin{tabular}{rrr}
\toprule
Observation 1 & Observation 2 & $\bar{X}$\\
\midrule
\cellcolor{gray!10}{10} & \cellcolor{gray!10}{10} & \cellcolor{gray!10}{10}\\
20 & 10 & 15\\
\cellcolor{gray!10}{30} & \cellcolor{gray!10}{10} & \cellcolor{gray!10}{20}\\
40 & 10 & 25\\
\cellcolor{gray!10}{10} & \cellcolor{gray!10}{20} & \cellcolor{gray!10}{15}\\
\addlinespace
20 & 20 & 20\\
\cellcolor{gray!10}{30} & \cellcolor{gray!10}{20} & \cellcolor{gray!10}{25}\\
40 & 20 & 30\\
\cellcolor{gray!10}{10} & \cellcolor{gray!10}{30} & \cellcolor{gray!10}{20}\\
20 & 30 & 25\\
\addlinespace
\cellcolor{gray!10}{30} & \cellcolor{gray!10}{30} & \cellcolor{gray!10}{30}\\
40 & 30 & 35\\
\cellcolor{gray!10}{10} & \cellcolor{gray!10}{40} & \cellcolor{gray!10}{25}\\
20 & 40 & 30\\
\cellcolor{gray!10}{30} & \cellcolor{gray!10}{40} & \cellcolor{gray!10}{35}\\
\addlinespace
40 & 40 & 40\\
\bottomrule
\end{tabular}
\end{table}

{The sampling distribution of \(\bar{X}\) is given by:}

\begin{table}[H]
\centering\centering
\begin{tabular}{rl}
\toprule
$\bar{X}$ & $P(\bar{X})$\\
\midrule
\cellcolor{gray!10}{10} & \cellcolor{gray!10}{$\color{red}{(0.1)^2=0.01}$}\\
15 & $\color{red}{2(0.1 \times 0.2)=0.04}$\\
\cellcolor{gray!10}{20} & \cellcolor{gray!10}{$\color{red}{2(0.1\times 0.3)+0.2^2=0.1}$}\\
25 & $\color{red}{2(0.4\times 0.1)+2(0.2\times 0.3)=0.2}$\\
\cellcolor{gray!10}{30} & \cellcolor{gray!10}{$\color{red}{2(0.2\times 0.4)+0.3^2=0.25}$}\\
\addlinespace
35 & $\color{red}{2(0.3\times 0.4)=0.24}$\\
\cellcolor{gray!10}{40} & \cellcolor{gray!10}{$\color{red}{(0.4)^2=0.16}$}\\
\bottomrule
\end{tabular}
\end{table}

\subsection{Deriving Probabilities From Discrete
Distributions}\label{deriving-probabilities-from-discrete-distributions}

\(\bf (9)\) Michael Dickson, who plays for the Seattle Seahawks, is a
punter in the NFL. The following sampling distribution gives the mean
punting distance (in yards) for a sample of \(n=4\) punts. Use this
distribution to answer the following questions:

\begin{table}[H]
\centering\centering
\begin{tabular}{rr}
\toprule
\$\textbackslash{}bar\{X\} =\$ Mean Punt Distance & \$P(\textbackslash{}bar\{X\})\$\\
\midrule
\cellcolor{gray!10}{35.33} & \cellcolor{gray!10}{0.40}\\
45.67 & 0.50\\
\cellcolor{gray!10}{55.00} & \cellcolor{gray!10}{0.08}\\
60.33 & 0.01\\
\cellcolor{gray!10}{65.67} & \cellcolor{gray!10}{0.01}\\
\bottomrule
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  What is the probability the mean distance is 55 or more yards?
\end{itemize}

{\[ P(\bar{X} \geq 55) = 1- P(\bar{X} < 55)\] \[ = 1-(0.4+0.5) = 0.1 \]}

\begin{itemize}
\tightlist
\item
  What is the probability the mean distance is at least 35.33 yards?
\end{itemize}

{\[ P(\bar{X} \geq 35.33) = 1\]}

\begin{itemize}
\tightlist
\item
  What is the probability the mean distance is between 35.33 and 45.67
  yards?
\end{itemize}

{ \[P(35.33\leq \bar{X} \leq 45.67) = P(X = 35.33)+P(X = 45.67) = 0.9\]
}

\begin{itemize}
\tightlist
\item
  What is the probability the mean distance is 35.33 yards or 55 yards?
\end{itemize}

{Let \(A\) be the event \(\bar{X} = 35.33\) and \(B\) be the event
\(\bar{X} = 55\). These outcomes are disjoint, so
\[P(A\cup B) = P(\bar{X} = 35.33)+P(\bar{X} = 55) = 0.4+0.08 = 0.48 \]}

\(\bf (10)\) A random variable \(X\) follows a binomial distribution
with probability of success \(p = 0.43\) and number of trials \(n = 8\).
What is the probability of observing fewer than 3 successes, that is
what is \(P(X < 3)\)?

{Let \(X \sim Binomial(p = 0.43, n = 8)\) then}

\[ \color{red}{P(X < 3) =  P(X = 0)+P(X = 1)+P(X = 2)}\]

\[ \color{red}{= \sum_{k = 0}^2 \frac{8!}{k!(8 - k)!} \times 0.43^{k} \times (1-0.43)^{8-k} \approx 0.256}\]

\(\bf (11)\) Tom Brady is a famous quarterback who recently retired from
playing in the National Football League. During his career, the
probability that Brady would complete a pass in a given play was
\(64.3\%\). If a typical NFL team runs about \(35\) offensive pass
plays, what is the probability that Brady would complete exactly \(28\)
pass plays in a game?

Let \(X \sim Binomial(p = 0.643, n = 35)\) then

\[\color{red}{P(X = 28) = \frac{35!}{28!(35 - 28)!} \times 0.643^{28}\times (1-0.643)^{35-28} \approx 0.021}\]

\(\bf (12)\) A random variable \(W\) follows a Poisson distribution with
rate parameter \(\lambda = 1.8\) events per hour. What is the
probability of observing exactly four events in a given hour, that is
what is \(P(W = 4)\)?

{Let \(W\sim Poisson(\lambda = 1.8)\)
\[P(W = 4) = \frac{1.8^4\cdot e^{-1.8}}{4!} \approx 0.072 \]}

\(\bf (13)\) A factory experiences on average 3 equipment malfunctions
per day, following a Poisson distribution with a rate parameter of 3.
Calculate the probability that on a randomly selected day, the factory
will observe 3 or more equipment malfunctions.

{let \(X\) represent the number of equipment failures in a given day for
the factory, then \[X\sim Poisson(\lambda = 3)\]
\[P(X\geq 3) = 1 - P(X< 3)\] where
\[P(X < 3) =  P(X = 0)+P(X = 1)+P(X = 2) = \sum_{k=0}^2 \frac{3^k\cdot e^{-3}}{k!} \approx 0.423\]
so \[P(X\geq 3) = 1 - 0.423 \approx 0.577\] }

\subsection{Deriving Probabilities From Continuous
Distributions}\label{deriving-probabilities-from-continuous-distributions}

\({\bf (14)}\) Use the plot below of the probability distribution of a
continuous random variable \(X\) to answer the following questions

\includegraphics{week7homework_solns_files/figure-latex/unnamed-chunk-12-1.pdf}

Use the plot to find the following probabilities:

\begin{itemize}
\tightlist
\item
  What is \(P(X<0.6)\)?
\end{itemize}

{ In this plot the area comprising a single grid square is
\[ \text{Area of a rectangle} = \text{Base}\times\text{Height} = 0.167\times 0.3 \approx 0.05\]
there are six grid squares between \(0\) and \(0.6\), therefore
\[P(X<0.6)= 6\times 0.05 = 0.3\]}

\begin{itemize}
\tightlist
\item
  What is \(P(X>0.3)\)?
\end{itemize}

{\(P(X>0.3)= 1-P(X\leq 0.3) = 1-(2*0.05) = 0.9\)}

\begin{itemize}
\tightlist
\item
  What is \(P(1.5<X<1.8)\)?
\end{itemize}

{\(P(1.5<X<1.8)=0.05\)}

\({\bf (15)}\) Use the plot below of the probability distribution of a
continuous random variable \(Y\) to answer the following questions

\includegraphics{week7homework_solns_files/figure-latex/unnamed-chunk-13-1.pdf}

Use the plot to find the following probabilities (recall that the area
of a triangle is
\(\frac{1}{2} \times \text{base} \times \text{height}\))

\begin{itemize}
\tightlist
\item
  What is \(P(Y>-0.25)\)?
\end{itemize}

{In this plot the area comprising a single grid square is
\[ \text{Area of a rectangle} = \text{Base}\times\text{Height} = 0.25\times 0.16 \approx 0.04\]
There are \(14\) grid squares in the area between \(-0.25\) and \(1.0\)
\(P(Y>-0.25)=14\times 0.04 = 0.56\)}

\begin{itemize}
\tightlist
\item
  What is \(P(-0.5<Y<0.25)\)?
\end{itemize}

{There are \(16\) grid squares in the area between \(-0.5\) and \(0.25\)
therefore \(P(-0.5<Y<0.25)=16\times 0.04 = 0.64\)}

\({\bf (16)}\) Use the plot below of the probability distribution of a
continuous random variable \(Z\) to answer the following questions

\includegraphics{week7homework_solns_files/figure-latex/unnamed-chunk-14-1.pdf}

Use the plot to find the following probabilities (recall that the area
of a triangle is
\(\frac{1}{2} \times \text{base} \times \text{height}\))

\begin{itemize}
\tightlist
\item
  What is \(P(Z<2)\)?
\end{itemize}

{\(P(Z<2)=0.5(2)(0.3) = 0.3\)}

\begin{itemize}
\tightlist
\item
  What is \(P(2<Z<3)\)?
\end{itemize}

{In this plot a single grid square has an area of \(0.05\) thus the area
between \(Z = 2\) and \(Z = 3\) is given by
\(P(2<Z<3)=2(0.05)+(0.5)(1)(0.2) = 0.2\)}

\begin{itemize}
\tightlist
\item
  What is \(P(Z>4)\)?
\end{itemize}

{\(P(Z>4) = P(Z<2) =0.3\)}

\begin{itemize}
\tightlist
\item
  Give the approximate value of the \(25th\) percentile of distribution
  of \(Z\)
\end{itemize}

{Reading from the plot, the area to the left of \(Z=2\) is \(0.3\), so
the \(25th\) percentile lies just below \(2\). Working it out exactly:
on \([0,2]\) the density is the line \(f(z) = 0.15z\), so the area to
the left of \(z\) is \(0.075z^2\). Setting \(0.075z^2 = 0.25\) gives
\[Q1 = \sqrt{0.25/0.075} \approx 1.83\]}

\({\bf 17.)}\) Assume the continuous random variable \(X\) follows a
normal distribution with mean \(\mu = 25\) and variance
\(\sigma^2 = 16\).

\includegraphics{week7homework_solns_files/figure-latex/unnamed-chunk-15-1.pdf}

Using a \(Z\)-table, find the following (approximate) probabilities for
\(X\). You can also use the app in the course website or
\href{http://www.statdistributions.com/normal/}{StatDistributions.com}
to check your result

\begin{itemize}
\tightlist
\item
  What is \(P(X<15)\)?
\end{itemize}

{\[ z = \frac{15-25}{4} = -2.5\] \[ P(Z<-2.5) = 0.006\]}

\begin{itemize}
\tightlist
\item
  What is \(P(X>28)\)?
\end{itemize}

{\[ z = \frac{28-25}{4} = 0.75\]
\[ P(Z>0.75) = 1-P(Z\leq 0.75) = 1-0.773 = 0.227\]}

\begin{itemize}
\tightlist
\item
  What is \(P(12<X<20)\)?
\end{itemize}

{\[ z_{\text{lower}} = \frac{12-25}{4} = -3.25\]
\[ z_{\text{upper}} = \frac{20-25}{4} = -1.25\]
\[ P(-3.25 < Z < -1.25) =   P(Z<-1.25) - P(Z<-3.25) = 0.106 - 0.001 = 0.105\]}

\begin{itemize}
\tightlist
\item
  What is \(P(X>30)\)?
\end{itemize}

{\[ z = \frac{30-25}{4} = 1.25\]
\[ P(Z>1.25) = 1-P(Z\leq 1.25) = 1-0.894 = 0.106 \]}

\begin{itemize}
\tightlist
\item
  What is \(P(25<X<33)\)?
\end{itemize}

{\[ z_{\text{lower}} = \frac{25-25}{4} = 0\]
\[ z_{\text{upper}} = \frac{33-25}{4} = 2\]
\[ P(0<Z<2) = P(Z<2) - P(Z<0) = 0.977 - 0.5 = 0.477\]}

\begin{itemize}
\tightlist
\item
  What is the value of \(X\) that marks the \(95th\) percentile of the
  distribution?
\end{itemize}

{the \(95th\) percentile of a standard normal distribution is
\(z=1.645\) plugging this into the \(z\)-score equation and solving for
\(X\) gives \[ (z\times \sigma) + \mu = (1.645\times 4) + 25 = 31.58 \]}

\begin{itemize}
\tightlist
\item
  What is the value of \(X\) that marks the \(40th\) percentile of the
  distribution?
\end{itemize}

{the \(40th\) percentile of a standard normal distribution is
\(z=-0.253\)
\[  (z\times \sigma) + \mu = (-0.253\times 4)+25 = 23.99 \approx 24.0 \]}

\({\bf 18.)}\) Suppose that a random variable \(X\) follows a normal
distribution with mean \(\mu = -5\) and standard deviation
\(\sigma = 1.8\). Using the plot of the \(Z\)-distribution below, shade
in the area corresponding to the probability \(P(-2< X <0.5)\)

{start by finding the
\(z\)-scores\[ P(-2<X<0.5) = P(X<0.5) - P(X<-2)  \]
\[ z_{\text{lower}} = \frac{-2 - (-5)}{1.8} = 1.67\]
\[ z_{\text{upper}} = \frac{0.5 - (-5)}{1.8} = 3.06\]
\[P(-2<X<0.5) = P(1.67< Z < 3.06)  \]}

\includegraphics{week7homework_solns_files/figure-latex/unnamed-chunk-16-1.pdf}

\newpage
\section{References}

\end{document}
