% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{float}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Homework 3},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Homework 3}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\subsubsection{Definitions}\label{definitions}

Define the following terms/concepts

\begin{itemize}
\item
  a.) Sampling Error
\item
  b.) Law of Large Numbers
\item
  c.) Sample Space
\item
  d.) Event
\item
  e.) Union
\item
  f.) Intersection
\item
  g.) Random Trial
\item
  h.) Random Variable
\item
  i.) Probability distribution
\item
  j.) Population distribution
\item
  k.) Continuous random variable
\item
  l.) Discrete random variable
\item
  m.) Probability Mass Function
\item
  n.) Probability Density Function
\end{itemize}

\subsection{Simple probability}\label{simple-probability}

\(\bf (1)\) A fair coin is thrown 3 times. What is the probability that
at least one heads is observed?

\(\bf (2)\) Suppose that in a class of 30 students, 8 students are in
band, 15 students play a sport, and 5 students are both in band and play
a sport. Let \(A\) be the event that a student is in band and let \(B\)
be the event that a student plays a sport. Create a Venn diagram that
models this situation. What is the probability that a student is in the
band or plays a sport?

\(\bf (3)\) A standard deck of 52 cards contains four suits (Hearts,
Diamonds, Clubs, and Spades). Each suit contains 13 cards (9 numbered
cards and 3 face cards, and an Ace).

\begin{itemize}
\tightlist
\item
  Suppose a single card is drawn at random, what is the probability that
  it is a numbered card?
\end{itemize}

\begin{itemize}
\tightlist
\item
  What is the probability that the selected card is the Ace of Spades
  (assume independence where necessary)?
\end{itemize}

\(\bf (4)\) An urn contains 5 green balls, 7 red balls, and 4 yellow
balls. Two balls are selected at random with replacement. What is the
probability that first ball is yellow and the second ball is red?

\(\bf (5)\) The probability that it rains \(R\) on a given day in
Moscow, Idaho is \(P(R) = 0.1\). The probability that it is Windy \(W\)
is \(P(W) = 0.2\), and the probability that it is cloudy \(C\) is
\(P(C) = 0.7\). Assume that these three types of weather events are
independent. What is the probability that a given day is Rainy, Cloudy,
and Windy?

\subsection{Sampling Distributions, Means, and
Variances}\label{sampling-distributions-means-and-variances}

\(\bf (6)\) A random variable \(X\) has the following probability
distribution

\begin{table}[H]
\centering\centering
\begin{tabular}{rr}
\toprule
X & P(X)\\
\midrule
\cellcolor{gray!10}{1} & \cellcolor{gray!10}{0.25}\\
2 & 0.25\\
\cellcolor{gray!10}{3} & \cellcolor{gray!10}{0.25}\\
4 & 0.25\\
\bottomrule
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  Derive the sampling distribution for the mean of \(n=2\) observations
  of \(X\)
\end{itemize}

\begin{itemize}
\tightlist
\item
  Compute the mean \(\mu_{\bar{X}}\) and standard deviation
  \(\sigma_{\bar{X}}\) of the sampling distribution of \(\bar{X}\)
\end{itemize}

\(\bf (7)\) A random variable \(Y\) has two possible outcomes. The
outcome \(Y = 1\) occurs with probability \(p = 0.23\). Derive the
sampling distribution for the proportion of outcomes with \(Y = 1\) in a
sample of \(n = 3\) observations of \(Y\).

\(\bf (8)\) Consider a survey of tree volume. Suppose that in the
population of trees \(10\%\) have a volume of 10 cubic feet, \(20\%\)
have a volume of 20 cubic feet, \(30\%\) have a volume of 30 cubic feet,
and \(40\%\) have a volume of 40 cubic feet. Let \(X\) denote the volume
of a randomly selected tree, assuming that every tree has an equal
chance of being selected. The probability distribution of \(X\) is given
in the table below.

\begin{table}[H]
\centering\centering
\begin{tabular}{rr}
\toprule
X & P(X)\\
\midrule
\cellcolor{gray!10}{10} & \cellcolor{gray!10}{0.1}\\
20 & 0.2\\
\cellcolor{gray!10}{30} & \cellcolor{gray!10}{0.3}\\
40 & 0.4\\
\bottomrule
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  Confirm that \(X\) has a mean of \(\mu = 30\) cubic feet and a
  standard deviation of \(\sigma = 10\) cubic feet by computing them
  yourself.
\end{itemize}

\begin{itemize}
\tightlist
\item
  Derive the sampling distribution for the mean tree volume in a sample
  of \(n = 2\) trees.
\end{itemize}

\subsection{Deriving Probabilities From Discrete
Distributions}\label{deriving-probabilities-from-discrete-distributions}

\(\bf (9)\) Michael Dickson, who plays for the Seattle Seahawks, is a
punter in the NFL. The following sampling distribution gives the mean
punting distance (in yards) for a sample of \(n=4\) punts. Use this
distribution to answer the following questions:

\begin{table}[H]
\centering\centering
\begin{tabular}{rr}
\toprule
\$\textbackslash{}bar\{X\} =\$ Mean Punt Distance & \$P(\textbackslash{}bar\{X\})\$\\
\midrule
\cellcolor{gray!10}{35.33} & \cellcolor{gray!10}{0.40}\\
45.67 & 0.50\\
\cellcolor{gray!10}{55.00} & \cellcolor{gray!10}{0.08}\\
60.33 & 0.01\\
\cellcolor{gray!10}{65.67} & \cellcolor{gray!10}{0.01}\\
\bottomrule
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  What is the probability the mean distance is 55 or more yards?
\end{itemize}

\begin{itemize}
\tightlist
\item
  What is the probability the mean distance is at least 35.33 yards?
\end{itemize}

\begin{itemize}
\tightlist
\item
  What is the probability the mean distance is between 35.33 and 45.67
  yards?
\end{itemize}

\begin{itemize}
\tightlist
\item
  What is the probability the mean distance is 35.33 yards or 55 yards?
\end{itemize}

\(\bf (10)\) A random variable \(X\) follows a binomial distribution
with probability of success \(p = 0.43\) and number of trials \(n = 8\).
What is the probability of observing fewer than 3 successes, that is
what is \(P(X < 3)\)?

\(\bf (11)\) Tom Brady is a famous quarterback who recently retired from
playing in the National Football League. During his career, the
probability that Brady would complete a pass in a given play was
\(64.3\%\). If a typical NFL team runs about \(35\) offensive pass
plays, what is the probability that Brady would complete exactly \(28\)
pass plays in a game?

\(\bf (12)\) A random variable \(W\) follows a Poisson distribution with
rate parameter \(\lambda = 1.8\) events per hour. What is the
probability of observing exactly four events in a given hour, that is
what is \(P(W = 4)\)?

\(\bf (13)\) A factory experiences on average 3 equipment malfunctions
per day, following a Poisson distribution with a rate parameter of 3.
Calculate the probability that on a randomly selected day, the factory
will observe 3 or more equipment malfunctions.

\subsection{Deriving Probabilities From Continuous
Distributions}\label{deriving-probabilities-from-continuous-distributions}

\({\bf (14)}\) Use the plot below of the probability distribution of a
continuous random variable \(X\) to answer the following questions

\includegraphics{week7homework_files/figure-latex/unnamed-chunk-4-1.pdf}

Use the plot to find the following probabilities:

\begin{itemize}
\tightlist
\item
  What is \(P(X<0.6)\)?
\end{itemize}

\begin{itemize}
\tightlist
\item
  What is \(P(X>0.3)\)?
\end{itemize}

\begin{itemize}
\tightlist
\item
  What is \(P(1.5<X<1.8)\)?
\end{itemize}

\({\bf (15)}\) Use the plot below of the probability distribution of a
continuous random variable \(Y\) to answer the following questions

\includegraphics{week7homework_files/figure-latex/unnamed-chunk-5-1.pdf}

Use the plot to find the following probabilities (recall that the area
of a triangle is
\(\frac{1}{2} \times \text{base} \times \text{height}\))

\begin{itemize}
\tightlist
\item
  What is \(P(Y>-0.25)\)?
\end{itemize}

\begin{itemize}
\tightlist
\item
  What is \(P(-0.5<Y<0.25)\)?
\end{itemize}

\({\bf (16)}\) Use the plot below of the probability distribution of a
continuous random variable \(Z\) to answer the following questions

\includegraphics{week7homework_files/figure-latex/unnamed-chunk-6-1.pdf}

Use the plot to find the following probabilities (recall that the area
of a triangle is
\(\frac{1}{2} \times \text{base} \times \text{height}\))

\begin{itemize}
\tightlist
\item
  What is \(P(Z<2)\)?
\end{itemize}

\begin{itemize}
\tightlist
\item
  What is \(P(2<Z<3)\)?
\end{itemize}

\begin{itemize}
\tightlist
\item
  What is \(P(Z>4)\)?
\end{itemize}

\begin{itemize}
\tightlist
\item
  Give the approximate value of the \(25th\) percentile of distribution
  of \(Z\)
\end{itemize}

\({\bf 17.)}\) Assume the continuous random variable \(X\) follows a
normal distribution with mean \(\mu = 25\) and variance
\(\sigma^2 = 16\).

\includegraphics{week7homework_files/figure-latex/unnamed-chunk-7-1.pdf}

Using a \(Z\)-table, find the following (approximate) probabilities for
\(X\). You can also use the app in the course website or
\href{http://www.statdistributions.com/normal/}{StatDistributions.com}
to check your result

\begin{itemize}
\tightlist
\item
  What is \(P(X<15)\)?
\end{itemize}

\begin{itemize}
\tightlist
\item
  What is \(P(X>28)\)?
\end{itemize}

\begin{itemize}
\tightlist
\item
  What is \(P(12<X<20)\)?
\end{itemize}

\begin{itemize}
\tightlist
\item
  What is \(P(X>30)\)?
\end{itemize}

\begin{itemize}
\tightlist
\item
  What is \(P(25<X<33)\)?
\end{itemize}

\begin{itemize}
\tightlist
\item
  What is the value of \(X\) that marks the \(95th\) percentile of the
  distribution?
\end{itemize}

\begin{itemize}
\tightlist
\item
  What is the value of \(X\) that marks the \(40th\) percentile of the
  distribution?
\end{itemize}

\({\bf 18.)}\) Suppose that a random variable \(X\) follows a normal
distribution with mean \(\mu = -5\) and standard deviation
\(\sigma = 1.8\). Using the plot of the \(Z\)-distribution below, shade
in the area corresponding to the probability \(P(-2< X <0.5)\)

\includegraphics{week7homework_files/figure-latex/unnamed-chunk-8-1.pdf}

\newpage
\section{References}

\end{document}
