<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="STAT 251 Section 01" />


<title>Week 16 Notes</title>

<script src="site_libs/header-attrs-2.28/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<!--
  Pre-paint theme resolution. Included via `includes: in_header:` so it lands in
  <head> and runs synchronously before first paint - that is what prevents a
  flash of the wrong theme on load.

  We ALWAYS set data-theme (never leave it unset), which lets site.css express
  dark mode as a plain `:root[data-theme="dark"]` block with no duplicated
  @media (prefers-color-scheme) rules.
-->
<script>
(function () {
  var stored = null;
  // localStorage THROWS (not returns null) in Safari private browsing and in
  // some file:// contexts - which is exactly how these pages get previewed
  // locally. An uncaught throw here would leave data-theme unset and kill
  // every dark-mode rule on the page.
  try { stored = window.localStorage.getItem('stat251-theme'); } catch (e) { stored = null; }

  var theme = (stored === 'dark' || stored === 'light') ? stored :
    (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');

  document.documentElement.setAttribute('data-theme', theme);
})();
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="assets/brand/uidaho-branding.css" type="text/css" />
<link rel="stylesheet" href="assets/brand/site.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">STAT251-01</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Syllabus
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="syllabus.html">Course Syllabus</a>
    </li>
    <li>
      <a href="Course_Schedule.html">Course Schedule</a>
    </li>
    <li>
      <a href="university_resources.html">University Resources</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Lectures
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Lecture Notes</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="lecturemenu1.html">Week 1</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="lecslidesindex.html">Lecture Slides</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Homeworks
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Assignments</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="homeworks/week1homework.html">Homework 1</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Solutions</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="homeworks/week1homework_solns.html">Hmwk 1 Solutions</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Data &amp; PDF Downloads</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="homeworks/homework_downloads.html#hw1">Homework 1</a>
        </li>
        <li>
          <a href="homeworks/homework_downloads.html">All downloads</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="homeworks/reading_and_book_problems.html">Reading &amp; Extra Problems</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Exam Study Guides
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="study_guides/exam1_study_guide.html">Exam 1 Study Guide</a>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Exam 1 Review</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="Review_problems/exam1_review_problems.html">Problems</a>
        </li>
        <li>
          <a href="Review_problems/exam1_review_problems_solns.html">Solutions</a>
        </li>
      </ul>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Course Project
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="project.html">Project Description</a>
    </li>
    <li>
      <a href="data.html">Data</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Resources
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="https://stat-tools.jmks-homelab.dev/">Tools/Calculators</a>
    </li>
    <li>
      <a href="sac_schedule.html">SAC schedule</a>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Tables</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="misc/Z_table.html">Z-table</a>
        </li>
        <li>
          <a href="misc/t_table.html">t-table</a>
        </li>
        <li>
          <a href="misc/chisq_table.html">Chi-square table</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">R code</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="misc/rcode_examples.html">plotting in R</a>
        </li>
        <li>
          <a href="misc/hp_r_code.html">Functions</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Extras</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="./misc/Non-Parametric-Tests-For-Two-Samples.html">Non-parametric Tests</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="misc/R_download_instructions.html">Downloading R/Rstudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Week 16 Notes</h1>
<h4 class="author">STAT 251 Section 01</h4>

</div>


<!-- Week 16: Dec 7, 9, 11 2026 - ANOVA (two lectures) + final exam Jeopardy review -->
<div id="lecture-33" class="section level1">
<h1>Lecture 33</h1>
<p>Earlier in the semester we compared the means of <strong>two</strong>
independent groups using a two-sample <span
class="math inline">\(t\)</span>-test. A great many real questions,
though, involve <strong>more than two</strong> groups. Does the effect
on plant growth depend on which of three fertilizers we use? Do four
teaching methods produce different average exam scores? Do five
varieties of wheat differ in average yield?</p>
<p>The method for answering questions like these is called the
<strong>Analysis of Variance</strong>, almost always shortened to
<strong>ANOVA</strong>. The name sounds like it is about variances, and
in a sense it is, but the question it answers is about
<strong>means</strong>. The central idea is one you have already met in
a different guise: we split the total variation in the response into a
part explained by the groups and a part left over, and then judge
whether the explained part is large enough to take seriously.</p>
<div id="why-not-just-run-several-two-sample-t-tests"
class="section level3">
<h3>Why not just run several two-sample <span
class="math inline">\(t\)</span>-tests?</h3>
<p>The obvious thing to try is to test every pair of groups separately.
With three groups <span class="math inline">\(A\)</span>, <span
class="math inline">\(B\)</span> and <span
class="math inline">\(C\)</span> that means three tests: <span
class="math inline">\(A\)</span> vs <span
class="math inline">\(B\)</span>, <span class="math inline">\(A\)</span>
vs <span class="math inline">\(C\)</span>, and <span
class="math inline">\(B\)</span> vs <span
class="math inline">\(C\)</span>. Why not do that?</p>
<p>The problem is that each test carries its own chance of a Type I
error. If you run one test at <span class="math inline">\(\alpha =
0.05\)</span>, you have a <span class="math inline">\(5\%\)</span>
chance of wrongly declaring a difference. But if you run several tests
and announce a finding when <em>any one</em> of them is significant, the
chance that at least one is a false alarm grows quickly. With <span
class="math inline">\(k\)</span> groups there are <span
class="math inline">\(\binom{k}{2}\)</span> pairs, and if the tests were
independent the probability of at least one false positive would be</p>
<p><span class="math display">\[ P(\text{at least one Type I error}) = 1
- (1 - \alpha)^{\binom{k}{2}} \]</span></p>
<table class=" lightable-classic table table-striped" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Number of groups <span class="math inline">\(k\)</span>
</th>
<th style="text-align:right;">
Number of pairwise tests
</th>
<th style="text-align:left;">
P(at least one Type I error)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
0.0500
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
0.1426
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
0.2649
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:left;">
0.4013
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:left;">
0.5367
</td>
</tr>
</tbody>
</table>
<p>With six groups you would be wrong more often than a coin flip. This
is called the <strong>multiple comparisons problem</strong>, and it is
the reason we do not simply test every pair. ANOVA replaces all of those
tests with a <strong>single</strong> test of one overall question:</p>
<p><span class="math display">\[ H_0: \mu_1 = \mu_2 = \cdots = \mu_k
\]</span></p>
<p><span class="math display">\[ H_A: \text{at least one } \mu_i \text{
differs from the others} \]</span></p>
<p>Notice how modest the alternative is. ANOVA does not claim to tell
you <em>which</em> means differ, or by how much — only that they are not
all the same. Finding out which ones differ is the subject of the next
lecture.</p>
</div>
<div id="the-idea-behind-the-analysis-of-variance"
class="section level3">
<h3>The idea behind the analysis of variance</h3>
<p>Suppose we measure a response in each of three groups. There are two
quite different reasons the observations are not all identical:</p>
<ul>
<li>observations <strong>within</strong> the same group differ from one
another, because individuals naturally vary; and</li>
<li>observations in <strong>different</strong> groups differ, because
the group means may not be the same.</li>
</ul>
<p>The first is noise. The second is signal. ANOVA compares the size of
the second to the size of the first. If the group means are far apart
<em>relative to</em> the scatter inside the groups, we have evidence
that the population means really do differ. If the group means are close
together compared with the noise, we do not.</p>
<p>The plot below shows the same three group means in two situations. On
the left the within-group scatter is small and the separation between
groups stands out clearly. On the right the group means sit in exactly
the same places, but the noise is so large that the separation is
unconvincing.</p>
<p><img src="lecturemenu16_files/figure-html/unnamed-chunk-2-1.png" width="960" /></p>
<p>The black bars mark the group means. They sit in the same places in
both panels — what changes is how believable the separation is. ANOVA
turns that visual judgement into a number.</p>
</div>
<div id="notation" class="section level3">
<h3>Notation</h3>
<p>Suppose we have <span class="math inline">\(k\)</span> groups.
Write</p>
<ul>
<li><span class="math inline">\(n_i\)</span> for the number of
observations in group <span class="math inline">\(i\)</span>, and <span
class="math inline">\(N = n_1 + n_2 + \cdots + n_k\)</span> for the
total sample size;</li>
<li><span class="math inline">\(y_{ij}\)</span> for the <span
class="math inline">\(j\)</span>th observation in group <span
class="math inline">\(i\)</span>;</li>
<li><span class="math inline">\(\bar{y}_i\)</span> for the mean of group
<span class="math inline">\(i\)</span> (the <strong>group
mean</strong>);</li>
<li><span class="math inline">\(\bar{y}\)</span> for the mean of all
<span class="math inline">\(N\)</span> observations together (the
<strong>grand mean</strong>).</li>
</ul>
</div>
<div id="partitioning-the-total-variation" class="section level3">
<h3>Partitioning the total variation</h3>
<p>Measure the total variation in the response as the sum of squared
deviations of every observation from the grand mean:</p>
<p><span class="math display">\[ SS_T = \sum_{i=1}^{k} \sum_{j=1}^{n_i}
(y_{ij} - \bar{y})^2 \]</span></p>
<p>This total splits into exactly two pieces. The
<strong>between-group</strong> sum of squares measures how far the group
means sit from the grand mean,</p>
<p><span class="math display">\[ SS_B = \sum_{i=1}^{k} n_i (\bar{y}_i -
\bar{y})^2 \]</span></p>
<p>and the <strong>within-group</strong> sum of squares measures how far
individual observations sit from their own group mean,</p>
<p><span class="math display">\[ SS_W = \sum_{i=1}^{k} \sum_{j=1}^{n_i}
(y_{ij} - \bar{y}_i)^2 \]</span></p>
<p>and these add up:</p>
<p><span class="math display">\[ SS_T = SS_B + SS_W \]</span></p>
<p>This should look familiar. In simple linear regression we split the
total variation the same way, into a part explained by the model and a
part left over, <span class="math inline">\(SS_T = SS_R + SS_E\)</span>.
ANOVA is the same idea with a categorical explanatory variable instead
of a quantitative one: <span class="math inline">\(SS_B\)</span> plays
the role of <span class="math inline">\(SS_R\)</span>, and <span
class="math inline">\(SS_W\)</span> plays the role of <span
class="math inline">\(SS_E\)</span>.</p>
</div>
<div id="from-sums-of-squares-to-the-f-statistic"
class="section level3">
<h3>From sums of squares to the <span
class="math inline">\(F\)</span>-statistic</h3>
<p>We cannot compare <span class="math inline">\(SS_B\)</span> and <span
class="math inline">\(SS_W\)</span> directly, because each is built from
a different number of free quantities. As always, we divide by degrees
of freedom to get a <strong>mean square</strong>, which is just a
variance:</p>
<p><span class="math display">\[ MS_B = \frac{SS_B}{k-1} \qquad\qquad
MS_W = \frac{SS_W}{N-k} \]</span></p>
<p>The between-group mean square has <span
class="math inline">\(k-1\)</span> degrees of freedom because it is
built from <span class="math inline">\(k\)</span> group means around one
grand mean. The within-group mean square has <span
class="math inline">\(N - k\)</span> degrees of freedom because each of
the <span class="math inline">\(k\)</span> groups contributes <span
class="math inline">\(n_i - 1\)</span>. The two add to <span
class="math inline">\(N-1\)</span>, the total degrees of freedom.</p>
<p>The test statistic is their ratio:</p>
<p><span class="math display">\[ F_0 = \frac{MS_B}{MS_W} =
\frac{SS_B/(k-1)}{SS_W/(N-k)} \sim F(k-1, \ N-k) \]</span></p>
<p>If <span class="math inline">\(H_0\)</span> is true and all the
population means really are equal, then the group means differ only by
chance, <span class="math inline">\(MS_B\)</span> and <span
class="math inline">\(MS_W\)</span> are both estimating the same
underlying variance, and <span class="math inline">\(F_0\)</span> should
be near <span class="math inline">\(1\)</span>. If the means genuinely
differ, <span class="math inline">\(MS_B\)</span> is inflated and <span
class="math inline">\(F_0\)</span> is large. Because only large values
of <span class="math inline">\(F_0\)</span> are evidence against <span
class="math inline">\(H_0\)</span>, <strong>the ANOVA <span
class="math inline">\(F\)</span>-test is always upper-tailed</strong> —
even though the alternative hypothesis is two-sided in spirit. The <span
class="math inline">\(p\)</span>-value is</p>
<p><span class="math display">\[ p\text{-value} = P(F &gt; F_0 \mid H_0
\ \text{true}) \]</span></p>
<p>The results are collected in an <strong>ANOVA table</strong>:</p>
<table class=" lightable-classic table table-striped" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Source
</th>
<th style="text-align:left;">
Sum of Squares
</th>
<th style="text-align:left;">
Degrees of Freedom
</th>
<th style="text-align:left;">
Mean Square
</th>
<th style="text-align:left;">
F-statistic
</th>
<th style="text-align:left;">
<span class="math inline">\(p\)</span>-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Between groups
</td>
<td style="text-align:left;">
<span class="math inline">\(SS_B = \sum n_i(\bar{y}_i -
\bar{y})^2\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(k-1\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(MS_B = SS_B/(k-1)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(F_0 = MS_B/MS_W\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(P(F &gt; F_0|H_0)\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Within groups (error)
</td>
<td style="text-align:left;">
<span class="math inline">\(SS_W = \sum\sum (y_{ij} -
\bar{y}_i)^2\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(N-k\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(MS_W = SS_W/(N-k)\)</span>
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
<span class="math inline">\(SS_T = \sum\sum (y_{ij} -
\bar{y})^2\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(N-1\)</span>
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
</tbody>
</table>
</div>
<div id="a-worked-example-by-hand" class="section level3">
<h3>A worked example by hand</h3>
<p>A greenhouse trial compares three fertilizers. Four plants are grown
with each, and the height of each plant is recorded in centimetres after
four weeks.</p>
<table class=" lightable-classic table table-striped" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Fertilizer
</th>
<th style="text-align:left;">
Heights (cm)
</th>
<th style="text-align:right;">
<span class="math inline">\(n_i\)</span>
</th>
<th style="text-align:right;">
Group mean <span class="math inline">\(\bar{y}_i\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:left;">
8, 10, 9, 9
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
9
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:left;">
12, 14, 13, 13
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
13
</td>
</tr>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:left;">
10, 11, 12, 11
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
11
</td>
</tr>
</tbody>
</table>
<p>Here <span class="math inline">\(k = 3\)</span>, each <span
class="math inline">\(n_i = 4\)</span>, and <span
class="math inline">\(N = 12\)</span>. The grand mean is</p>
<p><span class="math display">\[ \bar{y} = \frac{8 + 10 + \cdots +
11}{12} = 11 \]</span></p>
<p><strong>Step 1 — between-group sum of squares.</strong> Each group
has <span class="math inline">\(n_i = 4\)</span> observations:</p>
<p><span class="math display">\[ SS_B = 4(9 - 11)^2 + 4(13 - 11)^2 +
4(11 - 11)^2 = 16 + 16 + 0 = 32 \]</span></p>
<p><strong>Step 2 — within-group sum of squares.</strong> Deviations are
taken from each group’s <em>own</em> mean:</p>
<p><span class="math display">\[ SS_W = \underbrace{(-1)^2 + 1^2 + 0^2 +
0^2}_{\text{group A}} + \underbrace{(-1)^2 + 1^2 + 0^2 +
0^2}_{\text{group B}} + \underbrace{(-1)^2 + 0^2 + 1^2 +
0^2}_{\text{group C}} = 2 + 2 + 2 = 6 \]</span></p>
<p><strong>Step 3 — check the partition.</strong> <span
class="math inline">\(SS_T = SS_B + SS_W = 32 + 6 = 38\)</span>, which
matches the total sum of squared deviations from the grand mean.</p>
<p><strong>Step 4 — degrees of freedom and mean squares.</strong></p>
<p><span class="math display">\[ MS_B = \frac{SS_B}{k-1} = \frac{32}{2}
= 16 \qquad\qquad MS_W = \frac{SS_W}{N-k} = \frac{6}{9} = 0.667
\]</span></p>
<p><strong>Step 5 — the test statistic.</strong></p>
<p><span class="math display">\[ F_0 = \frac{MS_B}{MS_W} =
\frac{16}{0.667} = 24 \sim F(2, 9) \]</span></p>
<p><strong>Step 6 — the decision.</strong> The critical value at <span
class="math inline">\(\alpha = 0.05\)</span> is <span
class="math inline">\(F_{0.95}(2, 9) = 4.26\)</span>, and the <span
class="math inline">\(p\)</span>-value is</p>
<p><span class="math display">\[ P(F &gt; 24 \mid H_0 \ \text{true}) =
0.00025 \]</span></p>
<p>Since <span class="math inline">\(24 &gt; 4.26\)</span>, or
equivalently since <span class="math inline">\(0.00025 &lt;
0.05\)</span>, we <strong>reject <span
class="math inline">\(H_0\)</span></strong> and conclude that the three
fertilizers do not all produce the same mean plant height.</p>
<p>The completed ANOVA table:</p>
<table class=" lightable-classic table table-striped" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Source
</th>
<th style="text-align:left;">
Sum of Squares
</th>
<th style="text-align:left;">
Degrees of Freedom
</th>
<th style="text-align:left;">
Mean Square
</th>
<th style="text-align:left;">
F-statistic
</th>
<th style="text-align:left;">
<span class="math inline">\(p\)</span>-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Between groups
</td>
<td style="text-align:left;">
32
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
16
</td>
<td style="text-align:left;">
24
</td>
<td style="text-align:left;">
0.00025
</td>
</tr>
<tr>
<td style="text-align:left;">
Within groups
</td>
<td style="text-align:left;">
6
</td>
<td style="text-align:left;">
9
</td>
<td style="text-align:left;">
0.667
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
38
</td>
<td style="text-align:left;">
11
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
</tbody>
</table>
<p>R produces exactly the same table with the <code>aov()</code>
function:</p>
<pre class="r"><code>fert &lt;- data.frame(
  Fertilizer = rep(c(&#39;A&#39;,&#39;B&#39;,&#39;C&#39;), each = 4),
  Height = c(8, 10, 9, 9, 12, 14, 13, 13, 10, 11, 12, 11)
)

#fit the model with aov(response ~ group, data = dataframe)
model = aov(Height ~ Fertilizer, data = fert)

summary(model)</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Fertilizer   2     32  16.000      24 0.000247 ***
## Residuals    9      6   0.667                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="assumptions" class="section level3">
<h3>Assumptions</h3>
<p>The <span class="math inline">\(F\)</span>-test above is trustworthy
only when three conditions hold:</p>
<ol style="list-style-type: decimal">
<li><strong>Independence.</strong> The observations are independent of
one another, both within and between groups. This comes from how the
data were collected and cannot be fixed after the fact.</li>
<li><strong>Normality.</strong> The response is approximately normally
distributed within each group. As with the <span
class="math inline">\(t\)</span>-test, this matters most when the
samples are small.</li>
<li><strong>Equal variances.</strong> The population variances are the
same in every group. This is the assumption that makes it sensible to
pool all the within-group scatter into a single <span
class="math inline">\(MS_W\)</span>.</li>
</ol>
<p>A useful rule of thumb for the third condition: if the
<strong>largest group standard deviation is less than twice the
smallest</strong>, the equal-variance assumption is reasonable. We check
all three on real data in the next lecture.</p>
</div>
</div>
<div id="lecture-34" class="section level1">
<h1>Lecture 34</h1>
<p>Last time we built the ANOVA <span
class="math inline">\(F\)</span>-test and used it to reject the
hypothesis that three fertilizers produce the same mean plant height.
But rejecting <span class="math inline">\(H_0\)</span> leaves the
interesting question unanswered: the means are not all equal, so
<em>which</em> ones differ? Today we answer that, we check the
assumptions the <span class="math inline">\(F\)</span>-test rests on,
and we connect ANOVA back to two tests you already know.</p>
<div id="running-an-anova-in-r" class="section level3">
<h3>Running an ANOVA in R</h3>
<p>R ships with a data set called <code>PlantGrowth</code>, which
records the dried weight of plants grown under a control condition and
two different treatments, with ten plants in each group <span
class="citation">(Dobson 1983)</span>.</p>
<pre class="r"><code>#PlantGrowth is included with R - no package needed
data(&quot;PlantGrowth&quot;)

str(PlantGrowth)</code></pre>
<pre><code>## &#39;data.frame&#39;:    30 obs. of  2 variables:
##  $ weight: num  4.17 5.58 5.18 6.11 4.5 4.61 5.17 4.53 5.33 5.14 ...
##  $ group : Factor w/ 3 levels &quot;ctrl&quot;,&quot;trt1&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<p>Always plot the data before testing. Side-by-side boxplots show the
group centres and spreads at a glance:</p>
<pre class="r"><code>ggplot(PlantGrowth, aes(x = group, y = weight, fill = group)) +
  geom_boxplot(alpha = 0.5, outlier.shape = NA) +
  geom_jitter(width = 0.12, size = 2) +
  theme_bw() +
  theme(legend.position = &#39;none&#39;,
        axis.title = element_text(size = 13)) +
  xlab(&#39;Group&#39;) + ylab(&#39;Dried weight (g)&#39;)</code></pre>
<p><img src="lecturemenu16_files/figure-html/unnamed-chunk-8-1.png" width="768" /></p>
<p>The group means and standard deviations:</p>
<table class=" lightable-classic table table-striped" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Group
</th>
<th style="text-align:right;">
<span class="math inline">\(n_i\)</span>
</th>
<th style="text-align:right;">
Mean <span class="math inline">\(\bar{y}_i\)</span>
</th>
<th style="text-align:right;">
Standard deviation <span class="math inline">\(s_i\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
ctrl
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
5.032
</td>
<td style="text-align:right;">
0.583
</td>
</tr>
<tr>
<td style="text-align:left;">
trt1
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
4.661
</td>
<td style="text-align:right;">
0.794
</td>
</tr>
<tr>
<td style="text-align:left;">
trt2
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
5.526
</td>
<td style="text-align:right;">
0.443
</td>
</tr>
</tbody>
</table>
<p>Now the ANOVA:</p>
<pre class="r"><code>model = aov(weight ~ group, data = PlantGrowth)

summary(model)</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)  
## group        2  3.766  1.8832   4.846 0.0159 *
## Residuals   27 10.492  0.3886                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The <span class="math inline">\(F\)</span>-statistic is <span
class="math inline">\(F_0 = 4.85\)</span> on <span
class="math inline">\(2\)</span> and <span
class="math inline">\(27\)</span> degrees of freedom, with a <span
class="math inline">\(p\)</span>-value of <span
class="math inline">\(0.016\)</span>. Since <span
class="math inline">\(0.016 &lt; 0.05\)</span> we reject <span
class="math inline">\(H_0\)</span> and conclude that the three groups do
not all have the same mean dried weight.</p>
</div>
<div id="a-significant-f-does-not-tell-you-which-means-differ"
class="section level3">
<h3>A significant <span class="math inline">\(F\)</span> does not tell
you which means differ</h3>
<p>This is the point where it is tempting to look at the group means,
notice that <code>trt2</code> has the largest and <code>trt1</code> the
smallest, and announce that both treatments differ from the control. The
<span class="math inline">\(F\)</span>-test does not license any of
that. It says only that the three means are not all equal.</p>
<p>To find out <em>which</em> pairs differ we need a procedure that
compares pairs while keeping the overall Type I error rate at <span
class="math inline">\(\alpha\)</span> — exactly the problem that stopped
us running separate <span class="math inline">\(t\)</span>-tests in the
first place.</p>
</div>
<div id="multiple-comparisons-tukeys-honest-significant-difference"
class="section level3">
<h3>Multiple comparisons: Tukey’s Honest Significant Difference</h3>
<p>The standard tool is <strong>Tukey’s Honest Significant
Difference</strong> (HSD) <span class="citation">(Tukey 1949)</span>. It
compares every pair of group means and widens the intervals just enough
that the <span class="math inline">\(95\%\)</span> confidence level
applies to the whole <em>family</em> of comparisons at once, not to each
one separately. In R it is one line:</p>
<pre class="r"><code>TukeyHSD(model)</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = weight ~ group, data = PlantGrowth)
## 
## $group
##             diff        lwr       upr     p adj
## trt1-ctrl -0.371 -1.0622161 0.3202161 0.3908711
## trt2-ctrl  0.494 -0.1972161 1.1852161 0.1979960
## trt2-trt1  0.865  0.1737839 1.5562161 0.0120064</code></pre>
<p>Read the output one row at a time. <code>diff</code> is the
difference in sample means, <code>lwr</code> and <code>upr</code> give a
confidence interval for the true difference, and <code>p adj</code> is
the <span class="math inline">\(p\)</span>-value adjusted for the fact
that we are making three comparisons. <strong>A pair differs
significantly when its interval does not contain zero</strong>,
equivalently when <code>p adj</code> <span class="math inline">\(&lt;
\alpha\)</span>.</p>
<table class=" lightable-classic table table-striped" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Comparison
</th>
<th style="text-align:right;">
Difference in means
</th>
<th style="text-align:left;">
95% CI
</th>
<th style="text-align:right;">
Adjusted <span class="math inline">\(p\)</span>-value
</th>
<th style="text-align:left;">
Contains 0?
</th>
<th style="text-align:left;">
Conclusion
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
trt1-ctrl
</td>
<td style="text-align:right;">
-0.371
</td>
<td style="text-align:left;">
(-1.062, 0.320)
</td>
<td style="text-align:right;">
0.3909
</td>
<td style="text-align:left;">
yes
</td>
<td style="text-align:left;">
no evidence of a difference
</td>
</tr>
<tr>
<td style="text-align:left;">
trt2-ctrl
</td>
<td style="text-align:right;">
0.494
</td>
<td style="text-align:left;">
(-0.197, 1.185)
</td>
<td style="text-align:right;">
0.1980
</td>
<td style="text-align:left;">
yes
</td>
<td style="text-align:left;">
no evidence of a difference
</td>
</tr>
<tr>
<td style="text-align:left;">
trt2-trt1
</td>
<td style="text-align:right;">
0.865
</td>
<td style="text-align:left;">
(0.174, 1.556)
</td>
<td style="text-align:right;">
0.0120
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:left;">
means differ
</td>
</tr>
</tbody>
</table>
<p>The result is worth pausing on. The only significant pair is
<code>trt2</code> versus <code>trt1</code> (<span
class="math inline">\(p = 0.012\)</span>). <strong>Neither treatment
differs significantly from the control.</strong> The overall <span
class="math inline">\(F\)</span>-test told us the means are not all
equal, and Tukey tells us the reason is that the two treatments differ
from <em>each other</em> — not that either one beats the control. Had we
jumped straight from a significant <span
class="math inline">\(F\)</span> to “the treatments work”, we would have
reported something the data do not support.</p>
<p>An alternative you may see is the <strong>Bonferroni
correction</strong>, which simply tests each of the <span
class="math inline">\(m\)</span> pairs at level <span
class="math inline">\(\alpha/m\)</span> instead of <span
class="math inline">\(\alpha\)</span>. With three comparisons at <span
class="math inline">\(\alpha = 0.05\)</span>, each pair is tested at
<span class="math inline">\(0.0167\)</span>. It is easy to explain and
always valid, but it is more conservative than Tukey — it will miss real
differences more often — so Tukey’s HSD is generally preferred when all
pairwise comparisons are of interest.</p>
</div>
<div id="checking-the-assumptions" class="section level3">
<h3>Checking the assumptions</h3>
<p><strong>Equal variances.</strong> From the table of group standard
deviations above, the largest is <span
class="math inline">\(0.794\)</span> and the smallest is <span
class="math inline">\(0.443\)</span>. Since <span
class="math inline">\(0.794 &lt; 2 \times 0.443 = 0.886\)</span>, the
rule of thumb is satisfied.</p>
<p><strong>Normality and constant spread.</strong> As in regression, we
examine the residuals — the distance from each observation to its group
mean. A normal quantile plot checks normality, and a plot of residuals
against fitted values checks that the spread is similar across
groups.</p>
<pre class="r"><code>resid.df &lt;- data.frame(fitted = fitted(model), residual = residuals(model))

p1 &lt;- ggplot(resid.df, aes(sample = residual)) +
  stat_qq(size = 2) + stat_qq_line(colour = &#39;red&#39;) +
  theme_bw() + xlab(&#39;Theoretical quantiles&#39;) + ylab(&#39;Sample quantiles&#39;) +
  ggtitle(&#39;Normal Q-Q plot of residuals&#39;)

p2 &lt;- ggplot(resid.df, aes(x = fitted, y = residual)) +
  geom_point(size = 2) +
  geom_hline(yintercept = 0, colour = &#39;red&#39;) +
  theme_bw() + xlab(&#39;Fitted value (group mean)&#39;) + ylab(&#39;Residual&#39;) +
  ggtitle(&#39;Residuals vs fitted values&#39;)

ggarrange(p1, p2, ncol = 2)</code></pre>
<p><img src="lecturemenu16_files/figure-html/unnamed-chunk-13-1.png" width="960" /></p>
<p>The points in the Q-Q plot lie close to the diagonal, so normality is
reasonable. In the residual plot the three vertical strips have
comparable heights, which again supports equal variances.
<strong>Independence</strong> cannot be checked from these plots; it is
a question about how the plants were assigned and measured.</p>
</div>
<div id="connections-to-what-we-already-know" class="section level3">
<h3>Connections to what we already know</h3>
<p><strong>ANOVA with two groups is the pooled two-sample <span
class="math inline">\(t\)</span>-test.</strong> If <span
class="math inline">\(k = 2\)</span>, the ANOVA <span
class="math inline">\(F\)</span>-statistic is exactly the square of the
two-sample <span class="math inline">\(t\)</span>-statistic, and the two
tests give identical <span class="math inline">\(p\)</span>-values.
Dropping <code>trt2</code> and comparing the remaining two groups both
ways:</p>
<pre class="r"><code>two &lt;- PlantGrowth[PlantGrowth$group != &#39;trt2&#39;, ]
two$group &lt;- droplevels(two$group)

t.stat &lt;- t.test(weight ~ group, data = two, var.equal = TRUE)$statistic
f.stat &lt;- summary(aov(weight ~ group, data = two))[[1]][1, &#39;F value&#39;]

c(`t squared` = round(unname(t.stat)^2, 4), `F statistic` = round(f.stat, 4))</code></pre>
<pre><code>##   t squared F statistic 
##      1.4191      1.4191</code></pre>
<p><strong>ANOVA and regression are the same partition.</strong> In Week
15 the regression output ended with an omnibus <span
class="math inline">\(F\)</span>-statistic testing whether the predictor
explained a significant share of the variation in the response. That
test split <span class="math inline">\(SS_T\)</span> into <span
class="math inline">\(SS_R + SS_E\)</span>; ANOVA splits it into <span
class="math inline">\(SS_B + SS_W\)</span>. The arithmetic is identical
— only the kind of explanatory variable changes, from quantitative in
regression to categorical here.</p>
</div>
<div id="summary-carrying-out-a-one-way-anova" class="section level3">
<h3>Summary: carrying out a one-way ANOVA</h3>
<ol style="list-style-type: decimal">
<li><strong>Plot the data first.</strong> Side-by-side boxplots show
whether a difference is plausible before any test is run.</li>
<li><strong>State the hypotheses.</strong> <span
class="math inline">\(H_0: \mu_1 = \cdots = \mu_k\)</span> against <span
class="math inline">\(H_A:\)</span> at least one mean differs.</li>
<li><strong>Run the <span class="math inline">\(F\)</span>-test</strong>
with <code>aov()</code> and read the <span
class="math inline">\(p\)</span>-value. Remember it is always
upper-tailed.</li>
<li><strong>If you reject <span
class="math inline">\(H_0\)</span></strong>, follow up with Tukey’s HSD
to find <em>which</em> pairs differ. If you fail to reject, stop — there
is nothing to follow up.</li>
<li><strong>Check the assumptions</strong>: independence from the study
design, normality from a Q-Q plot of residuals, and equal variances from
the residual plot and the largest-versus-smallest standard deviation
rule.</li>
</ol>
</div>
<div id="references" class="section level3 unnumbered">
<h3 class="unnumbered">References</h3>
<div id="refs" class="references csl-bib-body hanging-indent"
entry-spacing="0">
<div id="ref-dobson1983" class="csl-entry">
Dobson, A. J. 1983. <em>An Introduction to Statistical Modelling</em>.
London: Chapman; Hall.
</div>
<div id="ref-tukey1949" class="csl-entry">
Tukey, John W. 1949. <span>“Comparing Individual Means in the Analysis
of Variance.”</span> <em>Biometrics</em> 5 (2): 99–114.
</div>
</div>
</div>
</div>

<!--
  Light/dark toggle. Included via `includes: after_body:`.

  Two ordering constraints, both load-bearing - do not "modernise" this:

  1. NOT wrapped in DOMContentLoaded / $(document).ready / defer.
     An after_body <script> runs synchronously during parsing, so the button is
     already in the DOM when rmarkdown's navbar script measures
     `$(".navbar").first().height() + 15` at ready-time to set body padding-top.
     Deferring would turn a guaranteed ordering into a race we'd lose - jQuery's
     ready queue is FIFO and the template registered its handler first, in <head>.

  2. A <button>, not an <a href="#">.
     rmarkdown's active-link script queries `a[href="..."]`; an anchor would get
     swept into that and would also jump the page to the top on click.

  It injects into .navbar-header (NOT .navbar-right) so the control stays visible
  at mobile widths - .navbar-right lives inside .navbar-collapse and is hidden
  below 768px until the hamburger is opened. Pages with no navbar at all (the
  homeworks/, misc/, study_guides/, Review_problems/ pages) get a floating button.
-->
<script>
(function () {
  var root = document.documentElement;
  var KEY = 'stat251-theme';

  var SUN = '<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" ' +
    'stroke-width="2" stroke-linecap="round" aria-hidden="true" focusable="false">' +
    '<circle cx="12" cy="12" r="4.2"/><path d="M12 2.2v2.4M12 19.4v2.4M2.2 12h2.4M19.4 12h2.4' +
    'M5.1 5.1l1.7 1.7M17.2 17.2l1.7 1.7M18.9 5.1l-1.7 1.7M6.8 17.2l-1.7 1.7"/></svg>';

  var MOON = '<svg viewBox="0 0 24 24" width="16" height="16" fill="currentColor" ' +
    'aria-hidden="true" focusable="false">' +
    '<path d="M20.7 14.6A8.6 8.6 0 0 1 9.4 3.3a8.6 8.6 0 1 0 11.3 11.3z"/></svg>';

  function paint(theme) {
    // Show the action, not the state: in dark mode the button offers "Light".
    var goingTo = theme === 'dark' ? 'light' : 'dark';
    btn.innerHTML = (theme === 'dark' ? SUN : MOON) +
      '<span class="theme-toggle-label">' + (goingTo === 'dark' ? 'Dark' : 'Light') + '</span>';
    btn.setAttribute('aria-pressed', theme === 'dark' ? 'true' : 'false');
    btn.setAttribute('title', 'Switch to ' + goingTo + ' mode');
  }

  var btn = document.createElement('button');
  btn.type = 'button';
  btn.className = 'theme-toggle';
  btn.setAttribute('aria-label', 'Toggle dark mode');
  paint(root.getAttribute('data-theme') || 'light');

  btn.addEventListener('click', function () {
    var next = root.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
    root.setAttribute('data-theme', next);
    paint(next);
    try { window.localStorage.setItem(KEY, next); } catch (e) { /* private mode; session-only */ }
  });

  var header = document.querySelector('.navbar .navbar-header');
  if (header) {
    btn.classList.add('theme-toggle-nav');
    header.appendChild(btn);
  } else {
    btn.classList.add('theme-toggle-floating');
    document.body.appendChild(btn);
  }
})();
</script>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
