---
title: "Syllabus"
output:
  html_document:
    keep_md: false   ## no-op; its only job is to keep html_document a MAP
                     ## so the _site.yml output block merges in. See _site.yml.
  pdf_document: default
header-includes: \usepackage{float} \usepackage{hyperref}
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# STAT 251 Statistical Methods Section 03
* **Instructor:** Jarred M. Kvamme (pronounced ``Kuh-Wah-mee"), PhD Candidate and instructor, Department of Bioinformatics and Computational Biology. **Email** [jarredk@uidaho.edu](jarredk@uidaho.edu). My office is in the basement level of Brink Hall - **Room Number B-17** - My office hours are 11:30AM - 2:30PM Monday, Wednesday, and Friday. I am also available to meet by appointment.
	
* **Teaching Assistant:** To be announced. **Email:** To be announced.

* **Meeting Time:** This course is scheduled to meet from 12:30PM-1:20PM MWF. The room is to be announced.
	
* **Learning Outcomes:** Introduction to statistical methods including statistical description, data displays, design of statistical studies, basic sampling methods, descriptive statistics, probability and sampling distributions; interval and point estimation, statistical inference in surveys and experiments, simple linear regression, and analysis of variance.
	
* **Prerequisites:** One of the following: Math 143 (with a ‘C’ or better), Math 160, Math 170, or sufficient score on SAT, ACT, or math placement test [see https://www.uidaho.edu/registrar/registration/placement](www.uidaho.edu/registrar/registration/placement)
	
* **Course Materials:**
  * **Textbook:** [Barbara Illowsky, Susan Dean, et. al. (2017). Introductory Statistics. OpenStax. Licensed under a Creative Commons Attribution 4.0 International License (CC BY 4.0).  OpenStax.org.](https://openstax.org/details/books/introductory-statistics-2e) You can either use the PDF version or buy a hard copy from various sites, including OpenStax.org, Amazon.com, etc.
			
  * **Calculator:** You will need any type of calculator that has the exponent and square-root function for homework and tests.

  * **Laptop:** A laptop is **required for examinations**. Examinations are proctored in class but delivered through **Canvas**, so you must bring a **fully charged laptop** to class on exam days.

  * **Course Website:** Course materials including lecture notes, homework assignments, study guides, this syllabus, and other materials can be found on the [course website](https://jarred6068.github.io/Kvamme_UI_STAT251/index.html)
	
* **Attendance:** Class attendance is required. Excluding holidays, examination and review days, and dead week, there are 35 days of class. You are permitted to miss up to four days of class with no penalty, so your attendance will be computed as the proportion of days attending out of a total of 31 days. Beyond those four days you may only be excused for appropriate documented university sanctioned events or extreme circumstances (such as sudden illness). If you cannot attend your courses for an extended time due to a health-related issue or family emergency (e.g., COVID or death in the family), you should file a [VandalCare](https://www.uidaho.edu/student-affairs/dean-of-students/vandalcare) Report or contact the [The Dean of Students](https://www.uidaho.edu/student-affairs/dean-of-students) so that the university can document your absence and contact your instructors. You should plan to reserve your four “free” days of non-attendance for other short-term absences due to illness or other reasons. You may not be counted as being in attendance if you are not engaged in class (e.g., sleeping, using your phone/computer), arrive to class late, or leave class early. Attendance will be recorded daily via a one-question quiz in [Canvas](https://canvas.uidaho.edu/courses/25778). 
	
* **Assessment:**
  * **Homework:** Homework assignments will be made available on the course website under the _Homeworks_ tab. There will be **5 homework assignments**, worth **10%** of your course grade altogether. Homework will be collected in class on the due dates, which are listed on the course website under the [_Course Schedule_](Course_Schedule.html) tab and in **Canvas**. Assignments must be completed in pen or pencil on paper (any type of paper is fine). Homework is graded as completed or not completed: a complete assignment receives full points, while a partial or late assignment receives half credit. Homework will not be handed back; after each assignment is collected, the answer key will be posted on the course website. Some exam problems are based on homework problems (although the numbers may be changed) so it is highly recommended that you complete all homework assignments in advance of each examination.
  
  * **Course Project:** In addition to homework, a course project will be assigned which is a designed to integrate and apply knowledge gained throughout the semester. Details for the course project are posted under the __Course Project__ tab in the [course website](https://jarred6068.github.io/Kvamme_UI_STAT251/index.html). The project will be due in **Canvas** on **12/18 at midnight**.
			
  * **Exams:** There will be 3 midterm examinations and each will be worth **50 points**. The tentative dates of these exams are **9/18, 10/16, 11/20**. Students will have the entire 50 minute class period to complete their exam. Examinations are **proctored in class but delivered through Canvas**, so you must bring a **fully charged laptop** on examination days. Calculators are permitted (and sometimes necessary) for examinations, but must not be capable of wireless communication. Notes and calculators used during the examination may not be shared. Students are expected to bring their own calculators and laptops on examination days. Study guides for examinations will be made available on the course website in the _study guides section_ typically two lecture days before the examination. Make-ups for missed examinations will only be permitted for documented university sanctioned events or in extreme circumstances. Notice of a missed examination due to a foreseeable absence must be given at least one week before the scheduled day of the examination. Notice of a missed examination due to unforeseeable absence must be made before the end of the day for which the examination was scheduled. If I contact you to schedule a make-up you must respond promptly (i.e., the same day) or you may not be able to make it up.
			
  * **Final Exam:** The final examination is held during finals week, **December 14--18, 2026**; the day, time and room are set by the Registrar. The final examination may not be taken at another time unless, as according to university policy, you have more than two final examinations on that day, or a conflict with a documented university sanctioned event. The amount of time permitted to complete the final examination is two hours (120 minutes). The final examination is like that of the other examinations except that it is comprehensive and longer. A study guide for the final examination will be made available. Policies regarding the first three examinations also apply to the final examination, except that you are permitted to use up to **five pages** of notes for the final examination (8.5 by 11 inches maximum, writing on both sides is fine).
			
  * **Grading:** The first three examinations altogether are worth $50\%$ of your course grade. Therefore, each examination is worth about $17\%$ of your course grade. The final examination is worth $20\%$ of your course grade. The remaining $30\%$ of your grade is divided between the course project ($15\%$), homework ($10\%$) and attendance ($5\%$). Letter grades for the course will be assigned according to the following rubric: A ($87.5\%-100\%$), B ($75\%-87.5\%$), C ($62.5\%-75\%$), D ($50\%-62.5\%$), F (less than $50\%$). Course grades are based solely on the examination scores, attendance, collected homeworks, the course project, and the grading rubric described above. Changes to the grading system (e.g., the grade rubric or the weights) will not result in any students getting a lower letter grade than that obtained using the system described above. Grades will be updated periodically in [Canvas](https://canvas.uidaho.edu/courses/25778) so that you may track your progress in the course.

* **Drop-in Tutoring:** The Statistics Assistance Center (SAC) is a free drop-in tutoring service located in the library [See link here](https://www.uidaho.edu/sci/mathstat/centers/sac) for more information. Tutoring is also available through Academic Support Programs [see link here](https://www.uidaho.edu/current-students/academic-support/asp/tcs/tutoring).
	
* **Academic Honesty:** You are responsible for being aware of the policies of the University of Idaho on academic honesty. See Section A-1 of Article II of the [Student Code of Conduct](https://www.uidaho.edu/student-affairs/dean-of-students/student-conduct/students). This includes but is not limited to cheating, facilitation of cheating, and furnishing false information or false representation. **Breaches of academic honesty will not be tolerated, and will result in a F for the course and referral to the Dean of Students for further disciplinary action**
	
* **Disability Access:** Reasonable accommodations are available for students who have documented temporary or permanent disabilities. All accommodations must be approved through the Center for Disability Access and Resources (CDAR) located in the Bruce M. Pitman Center, Suite 127 in order to notify your instructor(s) as soon as possible regarding accommodation(s) needed for the course. Contact CDAR at 208-885-6307 or [cdar@uidaho.edu](mailto:cdar@uidaho.edu). For more information follow the link [here](https://www.uidaho.edu/current-students/cdar).
	
* **Title IX:** University of Idaho is committed to creating a safe learning environment for all students. Consistent with this, UI policy and Title IX prohibit sexual misconduct, which includes sex or gender based harassment, sexual assault, intimate partner violence, stalking, and retaliation. If you have experienced any form of sexual misconduct, know that help and support are available. Please be aware that all University of Idaho employees are mandatory reporters and are required to report any information they receive about sexual misconduct to the university’s Title IX Coordinator within 24 hours (Idaho State Board Policy, Section I, I.T.). [see link](https://www.uidaho.edu/ocri/title-nine/resources) to learn more about which resources on campus and within our community are confidential. If you would like to report an incident, you may do so anonymously by visiting [www.uidaho.edu/vandalcare](https://www.uidaho.edu/student-affairs/dean-of-students/vandalcare?utm_campaign=vandal-care-reports&utm_content=bias-committee&utm_medium=varied&utm_source=sa-vandalcare) or you can directly contact the Office of Civil Rights and Investigations at **208-885-4285** or [ocri@uidaho.edu](ocri@uidaho.edu).