#Builds the two table images used on slide 3 of the Week 1 Lecture 2 deck
#(docs/lecture_slides/Week 1/Week1_Lecture2_Slides_1_12_2024.pptx).
#
#Slide 3 illustrates the population/sample distinction with two pictures: the
#whole population with the sampled rows marked, and those sampled rows on their
#own. They used to be a fabricated table of twenty Imperial stormtroopers,
#generated by the top of Data/make_example_data.R. They are now the twenty
#Adelie penguins measured at Torgersen Island in 2007 - a real, complete, finite
#population, which is what the slide's {x_1, ..., x_N} framing actually claims.
#
#IMPORTANT - the output sizes are not arbitrary. slide3.xml gives each picture a
#fixed frame:
#    population  6560360 x 4570937 EMU  -> aspect 1.43535
#    sample      5205425 x 1444905 EMU  -> aspect 3.60261
#PowerPoint stretches whatever image sits in the relationship to fill that frame,
#so an image with a different aspect ratio comes out visibly squashed. The
#logical sizes below reproduce the originals (1108x772 and 1106x307) exactly.
#Change them and you have to change slide3.xml to match.
#
#Rendering goes through headless Chrome rather than LaTeX or kableExtra because
#Chrome is already a build dependency (see build_site.R) whereas webshot2/magick
#are not installed. --force-device-scale-factor=2 doubles the pixel count while
#leaving the aspect ratio untouched, which keeps the tables sharp in the PDF
#export of the deck.

#----------------------------------------------------------------------------
#Locate ourselves, so the script works from any working directory.
this_file <- tryCatch(normalizePath(sys.frame(1)$ofile, winslash = "/"),
                      error = function(e) NA_character_)
if (is.na(this_file)) {
  args <- commandArgs(trailingOnly = FALSE)
  m <- grep("^--file=", args, value = TRUE)
  this_file <- if (length(m)) normalizePath(sub("^--file=", "", m[[1]]),
                                            winslash = "/") else NA_character_
}
if (is.na(this_file)) stop("Could not determine the script location; run it with Rscript.")
assets_dir <- dirname(this_file)

csv_path <- file.path(assets_dir, "penguins_torgersen_2007.csv")
pop_png  <- file.path(assets_dir, "lecture2_slide3_population.png")
samp_png <- file.path(assets_dir, "lecture2_slide3_sample.png")

#----------------------------------------------------------------------------
#The data. Species/Island/Year are constant across all twenty rows, so they
#belong in the caption rather than in three columns of identical text.
penguins <- read.csv(csv_path, check.names = FALSE, colClasses = "character",
                     na.strings = "NA")

SAMPLE_ROWS <- c(1, 7, 8, 14, 19)   #the indices the slide has always used
SHOW_COLS   <- c("Observation", "Bill Length (mm)", "Bill Depth (mm)",
                 "Flipper Length (mm)", "Body Mass (g)", "Sex")

stopifnot(nrow(penguins) == 20, all(SHOW_COLS %in% names(penguins)))

#Both kinds of gap in the table get named here. Observation 4 has no measurements
#at all; observations 9-12 were measured but could not be sexed. Naming only the
#first left four unexplained NAs sitting in the Sex column of the slide.
SOURCE_LINE <- paste0(
  "Source: Palmer Station Antarctica LTER. Gorman, K. B., Williams, T. D. and ",
  "Fraser, W. R. (2014). PLoS ONE 9(3):e90081. R package palmerpenguins (Horst, ",
  "Hill and Gorman, 2020). All twenty Ad&eacute;lie penguins at Torgersen Island, ",
  "2007; observation 4 was banded but not measured, and sex was not determined ",
  "for observations 9&ndash;12."
)

#----------------------------------------------------------------------------
#HTML. The look copies the booktabs tables it replaces: a heavy rule above the
#header and below the last row, one light rule under the header, no vertical
#rules anywhere, numbers right-aligned and text left-aligned.
#
#Sampled rows are bold, red AND carry a leading marker. The red alone is how the
#old images did it, but colour is the only channel there - anyone who cannot
#separate the reds from the blacks loses the entire point of the slide.
#
#Font sizes are in logical px, and the conversion to points on the slide is fixed
#by the frame the image is stretched into:
#    population  1108 px wide -> 7.17 in  =>  1 px ~ 0.47 pt
#    sample      1106 px wide -> 5.69 in  =>  1 px ~ 0.37 pt
#
#What caps the table text is HEIGHT, not width. The population frame is 5.0 in
#tall and has to hold a header plus twenty rows plus the source line, so a row
#gets about 0.22 in and the text cannot go far past ~13 pt however it is set.
#The sizes below sit just under that ceiling (~12 pt population, ~11 pt sample).
#Raising them further needs a taller frame in slide3.xml, not a bigger font here -
#the body has overflow:hidden, so text that no longer fits is silently CLIPPED
#rather than spilling somewhere visible. Always eyeball the PNGs after a change.
#
#Column headers are split over two lines at the unit, which is what the original
#booktabs images did ("Observation / Number", "Blaster / Accuracy"). That is what
#buys the horizontal room for the larger type.
esc <- function(x) {
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub("<", "&lt;",  x, fixed = TRUE)
  gsub(">", "&gt;", x, fixed = TRUE)
}

build_html <- function(rows, mark, font_px, row_px, head_px, source_line = NULL,
                       show_marker = TRUE, source_px = 16) {
  #Right-align everything except Sex, which is the one categorical column.
  align <- ifelse(SHOW_COLS == "Sex", "left", "right")
  align[SHOW_COLS == "Observation"] <- "left"

  #"Bill Length (mm)" -> "Bill Length" over "(mm)". Columns with no unit get a
  #blank second line so every header cell is the same two lines tall.
  head_txt <- vapply(SHOW_COLS, function(nm) {
    parts <- regmatches(nm, regexec("^(.*?)\\s*(\\(.*\\))$", nm))[[1]]
    if (length(parts) == 3) sprintf("%s<br>%s", esc(parts[[2]]), esc(parts[[3]]))
    else sprintf("%s<br>&nbsp;", esc(nm))
  }, character(1))

  head_cells <- paste0(
    sprintf('<th class="%s">%s</th>', align, head_txt), collapse = "")

  body <- vapply(seq_len(nrow(rows)), function(i) {
    vals <- as.character(unlist(rows[i, SHOW_COLS]))
    vals[is.na(vals)] <- "NA"
    #The marker goes in the Observation cell so it reads as part of the row
    #label rather than as an extra column.
    if (mark[i] && show_marker)
      vals[[1]] <- paste0("<span class=\"mk\">&#9656;</span>", vals[[1]])
    sprintf('<tr class="%s">%s</tr>',
            if (mark[i]) "sampled" else "",
            paste0(sprintf('<td class="%s">%s</td>', align, vals), collapse = ""))
  }, character(1))

  src <- if (is.null(source_line)) "" else
    sprintf('<p class="src">%s</p>', source_line)

  sprintf('<!doctype html><html><head><meta charset="utf-8"><style>
  html, body { margin:0; padding:0; width:100%%; height:100%%;
               background:#ffffff; overflow:hidden; }
  body { display:flex; flex-direction:column; justify-content:center;
         font-family:"Latin Modern Roman","CMU Serif","Latin Modern Roman 10",
                     "Times New Roman",Times,serif;
         font-size:%dpx; color:#000000; }
  table { width:100%%; border-collapse:collapse; table-layout:auto; }
  td { height:%dpx; padding:0 8px; white-space:nowrap; line-height:%dpx; }
  th { font-weight:normal; border-bottom:1px solid #000000; padding:0 8px;
       white-space:nowrap; line-height:%dpx; vertical-align:bottom; }
  thead tr { border-top:2.5px solid #000000; }
  tbody tr:last-child { border-bottom:2.5px solid #000000; }
  .left  { text-align:left; }
  .right { text-align:right; }
  tr.sampled td { color:#c00000; font-weight:bold; }
  .mk { display:inline-block; width:1.1em; }
  .src { margin:8px 10px 0 10px; font-size:%dpx; line-height:1.25;
         color:#000000; white-space:normal; }
</style></head><body>
<table><thead><tr>%s</tr></thead><tbody>%s</tbody></table>%s
</body></html>',
    font_px, row_px, row_px, head_px, source_px,
    head_cells, paste0(body, collapse = ""), src)
}

#----------------------------------------------------------------------------
#Chrome. Same discovery order as build_site.R, including the throwaway profile
#directory - without it headless Chrome fights the user's own running Chrome
#over the profile lock, which is the normal state of this machine.
find_chrome <- function() {
  chrome <- Sys.getenv("CHROME_BIN")
  if (nzchar(chrome) && file.exists(chrome)) return(chrome)
  candidates <- c(
    "C:/Program Files/Google/Chrome/Application/chrome.exe",
    "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
    "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",
    Sys.which(c("google-chrome", "chromium", "chromium-browser"))
  )
  candidates <- candidates[nzchar(candidates) & file.exists(candidates)]
  if (!length(candidates)) stop("Chrome not found; set CHROME_BIN.")
  candidates[[1]]
}

shoot <- function(html, out_png, w, h) {
  chrome  <- find_chrome()
  profile <- file.path(tempdir(), "slide3_chrome_profile")
  tmp     <- tempfile(fileext = ".html")
  writeLines(html, tmp, useBytes = TRUE)
  on.exit(unlink(tmp), add = TRUE)

  status <- system2(chrome, c(
    "--headless=new", "--disable-gpu", "--hide-scrollbars",
    paste0("--user-data-dir=", shQuote(profile)),
    "--force-device-scale-factor=2",
    "--virtual-time-budget=4000",
    paste0("--window-size=", w, ",", h),
    paste0("--screenshot=", shQuote(normalizePath(out_png, winslash = "/",
                                                  mustWork = FALSE))),
    shQuote(paste0("file:///", normalizePath(tmp, winslash = "/")))
  ), stdout = FALSE, stderr = FALSE)

  if (status != 0 || !file.exists(out_png))
    stop("Chrome failed to render ", basename(out_png), " (status ", status, ")")
  message("  ", basename(out_png), " (", w * 2, "x", h * 2, " px, ",
          format(file.size(out_png) %/% 1024L, big.mark = ","), " KB)")
}

#Overflow is clipped rather than reported, so check the height budget up front
#instead of discovering a missing bottom row by squinting at the slide.
check_fits <- function(label, canvas_px, n_rows, row_px, head_px,
                       source_px = 0, source_lines = 0) {
  used <- 2 * head_px + n_rows * row_px +
          if (source_lines > 0) 8 + ceiling(source_px * 1.25) * source_lines else 0
  if (used > canvas_px)
    stop(sprintf("%s does not fit: needs %d px of %d. Reduce row_px/head_px.",
                 label, used, canvas_px))
  message(sprintf("  %s: %d of %d px used (%d px spare)",
                  label, used, canvas_px, canvas_px - used))
}

#----------------------------------------------------------------------------
message("Rendering slide 3 tables from ", basename(csv_path))

mark_pop <- seq_len(nrow(penguins)) %in% SAMPLE_ROWS
#The source line wraps to three lines now that it accounts for the unsexed birds;
#that leaves only a few spare px of the 772, so eyeball the PNG after any change.
check_fits("population", 772, nrow(penguins), row_px = 32, head_px = 30,
           source_px = 16, source_lines = 3)
shoot(build_html(penguins, mark_pop, font_px = 26, row_px = 32, head_px = 30,
                 source_line = SOURCE_LINE, source_px = 16),
      pop_png, 1108, 772)

samp <- penguins[SAMPLE_ROWS, , drop = FALSE]
stopifnot(!anyNA(samp[, SHOW_COLS]))   #the n=5 table must have no gaps
check_fits("sample", 307, nrow(samp), row_px = 44, head_px = 40)
shoot(build_html(samp, rep(TRUE, nrow(samp)), font_px = 30, row_px = 44,
                 head_px = 40, show_marker = FALSE),
      samp_png, 1106, 307)

message("Done. Copy these into the deck with the swap step in the plan.")
